import type { GlossaryCard } from "../types";

// The school's own keyword lists (AA Glossary, AA & AN knowledge organisers,
// AN Word Glossary) — her test will expect these definitions.

export const GLOSSARY: GlossaryCard[] = [
  // ---- Acids & Alkalis ----
  { topic: "aa", term: "Acid", definition: "A substance that turns litmus red. It has a pH of less than 7.", example: "Citric acid in lemons, ethanoic acid in vinegar." },
  { topic: "aa", term: "Alkali", definition: "A substance that turns litmus blue. It has a pH of more than 7. A soluble base.", example: "Sodium hydroxide; oven cleaner contains a strong alkali." },
  { topic: "aa", term: "Base", definition: "Any substance, soluble or insoluble, that neutralises an acid, forming a salt and water.", example: "Metal oxides, metal hydroxides and metal carbonates are bases." },
  { topic: "aa", term: "Antacid", definition: "An indigestion remedy that contains a base to neutralise the excess acid in the stomach." },
  { topic: "aa", term: "Neutral", definition: "A substance that is neither an acid nor an alkali. It has a pH of 7.", example: "Pure water." },
  { topic: "aa", term: "Neutralisation", definition: "A reaction in which an acid reacts with an alkali or a base to produce a salt and water.", example: "acid + alkali → salt + water" },
  { topic: "aa", term: "Salt", definition: "The substance (other than water) that is formed when an acid reacts with an alkali or a base.", example: "Sodium chloride, potassium nitrate, magnesium sulfate." },
  { topic: "aa", term: "Sodium chloride", definition: "The chemical name for table (common) salt." },
  { topic: "aa", term: "Indicator", definition: "A dye that changes to different colours in acids and alkalis.", example: "Litmus, red cabbage, universal indicator." },
  { topic: "aa", term: "Litmus paper", definition: "An indicator that can be red or blue. Red litmus turns blue in alkalis; blue litmus turns red in acids." },
  { topic: "aa", term: "Universal indicator", definition: "A substance that turns different colours depending on the pH of a solution, and can detect pH across the whole pH range." },
  { topic: "aa", term: "pH scale", definition: "A numerical scale showing how acidic or alkaline a substance is. Acids have a pH below 7, neutral substances pH 7, and alkalis a pH above 7.", example: "Your organiser shows 0–14." },
  { topic: "aa", term: "Concentrated", definition: "A solution that contains a large amount of solute dissolved in a small amount of liquid (solvent)." },
  { topic: "aa", term: "Diluted", definition: "A substance that has had water added to it to make it less concentrated.", example: "Dilute acids have fewer acid particles in the same volume, so they are less dangerous." },
  { topic: "aa", term: "Corrosive", definition: "A corrosive substance can destroy metals, stonework and skin.", example: "Found on concentrated acids and alkalis." },
  { topic: "aa", term: "Hazard", definition: "Something that could cause harm." },
  { topic: "aa", term: "Risk", definition: "The chance that a hazard will actually cause harm." },
  { topic: "aa", term: "Precaution", definition: "An action taken to reduce the risk of a hazard causing harm.", example: "Wearing eye protection when handling an acid." },
  { topic: "aa", term: "Soluble", definition: "Describes a substance that can dissolve in a liquid." },
  { topic: "aa", term: "Insoluble", definition: "Describes a substance that cannot be dissolved in a liquid." },
  { topic: "aa", term: "Chemical reaction", definition: "A change in which new substances are made." },
  { topic: "aa", term: "Reactant", definition: "The substances that take part in a chemical reaction — written on the LEFT of the arrow in a word equation." },
  { topic: "aa", term: "Product", definition: "The new substances made in a chemical reaction — written on the RIGHT of the arrow in a word equation." },
  { topic: "aa", term: "Word equation", definition: "Names of the reactants on the left, an arrow pointing left to right, and names of the products on the right: reactants → products." },

  // ---- Animal Nutrition ----
  { topic: "an", term: "Digestion", definition: "The breakdown of large insoluble food molecules into small soluble ones.", example: "Starch in bread is broken down into sugars by amylase." },
  { topic: "an", term: "Digestive system", definition: "The organ system involved in breaking food down so that it can be absorbed into the bloodstream." },
  { topic: "an", term: "Absorbed", definition: "When a substance is taken in, or moved across a barrier such as a cell membrane." },
  { topic: "an", term: "Carbohydrates", definition: "Nutrient for energy.", example: "Bread, rice and pasta." },
  { topic: "an", term: "Proteins", definition: "Nutrient for growth and repair.", example: "Lentils, beans, tofu, paneer, milk." },
  { topic: "an", term: "Fats (lipids)", definition: "Nutrient for stored energy and insulation.", example: "Butter, oil, nuts." },
  { topic: "an", term: "Vitamins", definition: "Needed in small amounts for healthy body maintenance.", example: "Vitamin C (oranges) helps the immune system fight colds." },
  { topic: "an", term: "Minerals", definition: "Needed for healthy bones, teeth, blood, eyes, hair etc.", example: "Calcium in milk keeps bones and teeth strong." },
  { topic: "an", term: "Fibre", definition: "Aids digestion — keeps food and faeces moving along the digestive system. It cannot be digested.", example: "Wholegrain cereal, vegetables." },
  { topic: "an", term: "Starch test", definition: "Iodine solution turns from orange-brown to blue-black if starch is present." },
  { topic: "an", term: "Sugar (glucose) test", definition: "Benedict's solution, heated in a hot water bath, changes from blue to green, yellow, orange or brick red if sugar is present.", example: "Brick red = lots of sugar." },
  { topic: "an", term: "Protein test", definition: "Biuret reagent (potassium hydroxide + copper sulfate) turns from blue to purple/lilac if protein is present." },
  { topic: "an", term: "Fat test", definition: "Shake the food with ethanol, then add water: a milky white layer (emulsion) shows fat is present." },
  { topic: "an", term: "Enzyme", definition: "A protein that catalyses (speeds up) a chemical reaction. Enzymes are not living and are not used up." },
  { topic: "an", term: "Carbohydrase", definition: "Enzyme that breaks down carbohydrates (e.g. starch) into small soluble sugars such as glucose.", example: "Amylase and maltase are carbohydrases." },
  { topic: "an", term: "Amylase", definition: "An enzyme (a carbohydrase) that breaks down starch into simple sugars (maltose).", example: "Found in saliva and made by the pancreas." },
  { topic: "an", term: "Protease", definition: "Enzyme that breaks down proteins into amino acids.", example: "Works in the stomach and small intestine." },
  { topic: "an", term: "Lipase", definition: "Enzyme that breaks down lipids (fats and oils) into fatty acids and glycerol.", example: "Works in the small intestine." },
  { topic: "an", term: "Mouth", definition: "Where digestion begins — mechanical (chewing) and chemical (amylase in saliva)." },
  { topic: "an", term: "Oesophagus", definition: "The gullet: the tube from the mouth to the stomach. Muscle contractions push food down." },
  { topic: "an", term: "Stomach", definition: "Churns and mixes food with hydrochloric acid and enzymes. The acid kills bacteria and gives the right conditions for protease." },
  { topic: "an", term: "Liver", definition: "Makes bile.", example: "Bile emulsifies fat — breaks it UP, not down." },
  { topic: "an", term: "Bile", definition: "A substance made in the liver that emulsifies fats (big droplets → small droplets) to prepare them for digestion. It is not an enzyme." },
  { topic: "an", term: "Pancreas", definition: "Produces digestive enzymes (biological catalysts) that are released into the small intestine." },
  { topic: "an", term: "Small intestine", definition: "Where digestion finishes and digested food (glucose, amino acids, fatty acids, glycerol) is absorbed into the blood." },
  { topic: "an", term: "Villi", definition: "Finger-like projections in the small intestine that give a large surface area for absorbing food." },
  { topic: "an", term: "Capillary", definition: "A tiny blood vessel with walls one cell thick, where materials are exchanged." },
  { topic: "an", term: "Surface area", definition: "The area of the surface of an organism or membrane. Bigger surface area = faster absorption." },
  { topic: "an", term: "Large intestine", definition: "Absorbs water from undigested food, making the faeces solid." },
  { topic: "an", term: "Rectum", definition: "Stores faeces (undigested waste) before it leaves the body." },
  { topic: "an", term: "Anus", definition: "Where faeces leave the body." },
  { topic: "an", term: "Malnutrition", definition: "A poor (unbalanced) diet leading to health problems.", example: "Not enough protein can make children very weak." },
  { topic: "an", term: "Dehydration", definition: "Not enough water in the body.", example: "Can make you tired and give you a headache." },
  { topic: "an", term: "Obesity", definition: "Being very overweight, leading to health problems.", example: "Eating more energy than you use — the extra is stored as fat." },
];
