import type { MCQ, QuestionSet } from "../types";

export const MCQ_SET_2: QuestionSet<MCQ> = {
  id: "mcq-2",
  title: "Set 2 · Animal Nutrition",
  subtitle: "Nutrients, food tests, digestion and absorption",
  topic: "an",
  questions: [
    // ───────────────────────── WARMUP ─────────────────────────
    {
      id: "s2-q01",
      topic: "an",
      section: "an-nutrients",
      difficulty: "warmup",
      question: "Rice, bread and pasta are all rich in carbohydrates. What is the main job of carbohydrates in your body?",
      options: [
        "To help the body grow and repair itself",
        "To keep your bones and teeth strong",
        "To provide your body with energy",
        "To insulate the body and keep it warm",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Growth and repair is a vital job, which makes it tempting — but it belongs to protein (in lentils, beans, tofu and paneer), not carbohydrates.",
        "Strong bones and teeth matter, but they need minerals such as calcium, found in milk and cheese — carbohydrates don't do this job.",
        "Carbohydrates, like the starch in rice, bread and pasta, are your body's main source of energy.",
        "Fats and carbohydrates are both linked to energy, so they're easy to mix up — but insulation (keeping you warm) is a job of fats, not carbohydrates.",
      ],
      explanation:
        "**Carbohydrates are for energy.** Starchy foods such as rice, bread, pasta and potatoes are digested into sugars like glucose, which your body uses as fuel for everything from running to thinking. Each nutrient has its own job: **proteins** for growth and repair, **fats** for stored energy and insulation, and **minerals** such as calcium for strong bones and teeth. Memory trick: carbohydrates are the body's petrol — they keep the engine running.",
      hints: ["Think about why runners often eat a big plate of pasta the night before a race."],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q02",
      topic: "an",
      section: "an-nutrients",
      difficulty: "warmup",
      question: "Which nutrient does your body mainly use for growth and repair?",
      options: ["Protein", "Carbohydrate", "Fat", "Fibre"],
      answerIndex: 0,
      optionFeedback: [
        "Protein is broken down into amino acids, which your body uses to build new cells for growth and to repair damaged ones.",
        "Carbohydrates are in so many of the foods we eat that they're a natural guess — but their job is to give you energy, not to build the body.",
        "Fat is useful for stored energy and for insulation, which can make it seem important for the body — but it isn't the nutrient used for growth and repair.",
        "Fibre is important for a healthy gut, but it can't be digested or absorbed, so it can never be used to build the body.",
      ],
      explanation:
        "**Proteins are for growth and repair.** When you digest protein it is broken down into **amino acids**, which are absorbed into the blood and used to build new cells — so you can grow, and so damaged parts of your body can be repaired. Great vegetarian sources include lentils (dal), beans, chickpeas, tofu, paneer, cheese and milk. Memory trick: carbohydrates are the fuel, proteins are the building blocks.",
      hints: ["Which nutrient is digested into amino acids — the body's 'building blocks'?"],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q03",
      topic: "an",
      section: "an-food-tests",
      difficulty: "warmup",
      question: "Iodine solution is dropped onto a slice of raw potato, which contains starch. What colour does the iodine turn?",
      options: ["Purple", "Brick red", "Orange-brown", "Blue-black"],
      answerIndex: 3,
      optionFeedback: [
        "Purple is a dark colour like the real answer, so it's easy to pick — but purple (lilac) is the biuret result for protein, not the iodine result for starch.",
        "Brick red is a positive food-test colour, but it belongs to Benedict's solution heated with sugar — a different test for a different nutrient.",
        "Orange-brown is the colour iodine starts as. It would only stay orange-brown if there were no starch — and potato is full of starch.",
        "Iodine changes from orange-brown to blue-black when starch is present, and potato is very starchy.",
      ],
      explanation:
        "The **iodine test** is the test for **starch**. Iodine solution starts **orange-brown** and turns **blue-black** if starch is present; if it stays orange-brown, there is no starch. Potato, rice, bread and pasta all give a blue-black result. Memory trick: **star**ch turns iodine the colour of a **star**ry night sky — blue-black.",
      hints: ["Iodine starts orange-brown. Remember which food tests the other colours belong to."],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q04",
      topic: "an",
      section: "an-bile",
      difficulty: "warmup",
      question: "Bile helps your body deal with the fat in foods like cheese and butter. Which organ makes bile?",
      options: ["Gall bladder", "Liver", "Pancreas", "Stomach"],
      answerIndex: 1,
      optionFeedback: [
        "The gall bladder is tempting because bile is kept there — but it only stores bile. Bile is made in the liver.",
        "Bile is made in the liver, then stored in the gall bladder until it is released into the small intestine.",
        "The pancreas also sends juices into the small intestine, which makes it easy to confuse — but it makes enzymes, not bile.",
        "The stomach makes its own digestive juice, but that is hydrochloric acid and protease, not bile. In fact, alkaline bile helps neutralise the stomach acid later on.",
      ],
      explanation:
        "**Bile is made in the liver**, stored in the **gall bladder**, and released into the **small intestine**. There it **emulsifies** fats — breaking big fat droplets into lots of small droplets — so lipase can digest them faster. Bile is also alkaline, so it helps neutralise the acid arriving from the stomach. Memory trick: the liver **makes** it, the gall bladder **takes** it (and stores it).",
      hints: ["Careful: the organ that stores bile is not the one that makes it."],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q05",
      topic: "an",
      section: "an-absorption",
      difficulty: "warmup",
      question: "Which organ's main job is to absorb water from undigested food, making the faeces solid?",
      options: ["Small intestine", "Rectum", "Large intestine", "Stomach"],
      answerIndex: 2,
      optionFeedback: [
        "The small intestine is tempting because it is where absorption happens — but its main job is absorbing digested food such as glucose and amino acids, not drying out the leftovers.",
        "The rectum is where faeces end up, so it's easy to pick — but it only stores faeces until they leave the body through the anus.",
        "The large intestine absorbs water from undigested food, which turns the leftover waste into solid faeces.",
        "The stomach is full of liquid as it churns food, which makes it tempting — but its job is mixing food with acid and enzymes, not removing water from undigested food.",
      ],
      explanation:
        "Once the small intestine has absorbed the digested food, the leftover **undigested food** (such as fibre) moves into the **large intestine**. Here **water is absorbed** into the blood, so the waste becomes solid **faeces**. The faeces are stored in the **rectum** and leave the body through the **anus**. Memory trick: the **L**arge intestine is the **L**ast chance to save water before the waste leaves.",
      hints: ["Follow the food: where do the leftovers go after the small intestine has absorbed the digested food?"],
      strategy: "Follow the food",
    },
    {
      id: "s2-q06",
      topic: "an",
      section: "an-enzymes",
      difficulty: "warmup",
      question: "Butter, ghee and cooking oil are rich in lipids (fats and oils). Which enzyme breaks down lipids?",
      options: ["Lipase", "Protease", "Amylase", "Bile"],
      answerIndex: 0,
      optionFeedback: [
        "Lipase is the enzyme that breaks lipids down into fatty acids and glycerol.",
        "Protease is a digestive enzyme, so it sounds possible — but it breaks down protein, not fats and oils.",
        "Amylase is a well-known digestive enzyme, but it is a carbohydrase: it breaks starch into sugars, not fats.",
        "Bile does help with fat, which makes it tempting — but bile is not an enzyme. It only breaks fat into small droplets; lipase does the actual digesting.",
      ],
      explanation:
        "**Lipase** digests **lipids** (fats and oils) into **fatty acids and glycerol** in the small intestine. Enzyme names usually come from what they break down, plus **-ase**: **lip**id → **lip**ase, **prote**in → **prote**ase, **carbohydr**ate → **carbohydr**ase. Bile helps by breaking fat into small droplets first, but bile is not an enzyme.",
      hints: ["Enzyme names usually come from the name of the food molecule they break down, with '-ase' on the end."],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q07",
      topic: "an",
      section: "an-system",
      difficulty: "warmup",
      question: "What is the oesophagus, and what does it do?",
      options: [
        "The bag-shaped organ that churns food with acid",
        "The tube that carries air down to the lungs",
        "The long tube where digested food is absorbed into the blood",
        "The gullet — the tube that takes food from mouth to stomach",
      ],
      answerIndex: 3,
      optionFeedback: [
        "The stomach is joined to the bottom of the oesophagus, so they're easy to mix up — but churning food with acid is the stomach's job; the oesophagus is the tube leading to it.",
        "That's the windpipe, which sits right next to the oesophagus in your throat — easy to confuse, but the oesophagus carries food, not air.",
        "That's a tube in the digestive system, but absorbing digested food into the blood is the job of the small intestine, much further along.",
        "The oesophagus (gullet) connects the mouth to the stomach, and muscles in its wall squeeze each swallowed mouthful down.",
      ],
      explanation:
        "The **oesophagus**, also called the **gullet**, is the tube that connects your **mouth** to your **stomach**. When you swallow, muscles in its wall contract in waves to push the food down — which is why food still reaches your stomach even if you swallow while upside down. Its job is simply to move food from the mouth to the stomach.",
      hints: ["Think about where food goes straight after you swallow it."],
      strategy: "Follow the food",
    },

    // ───────────────────────── CORE ─────────────────────────
    {
      id: "s2-q08",
      topic: "an",
      section: "an-enzymes",
      difficulty: "core",
      question: "Bread and rice contain lots of starch. What does carbohydrase break starch down into?",
      options: ["Amino acids", "Sugars such as glucose", "Fatty acids", "Glycerol"],
      answerIndex: 1,
      optionFeedback: [
        "Amino acids are a product of digestion, so they sound right — but they come from protein (digested by protease), not from starch.",
        "Starch is a huge molecule made of many sugar units joined together, so carbohydrase breaks it into small, soluble sugars such as glucose.",
        "Fatty acids are a product of digestion too, but they come from lipids (fats and oils) digested by lipase, not from starch.",
        "Glycerol is a small digestion product, but it is made when lipase digests fats, alongside fatty acids — not from starch.",
      ],
      explanation:
        "Each digestive enzyme has its own products: **carbohydrase** (such as amylase) breaks **starch → sugars such as glucose**, **protease** breaks protein → amino acids, and **lipase** breaks lipids → fatty acids and glycerol. Starch is a huge, insoluble molecule made of lots of sugar units joined in a chain, so breaking it apart releases small, soluble sugars that can be absorbed into the blood. Try it: chew a piece of bread for a long time and it starts to taste sweet, because amylase in your saliva is turning starch into sugar.",
      hints: [
        "Starch is a carbohydrate. What are big carbohydrate molecules built from?",
        "Two of the options come from digesting fats, and one comes from digesting protein.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s2-q09",
      topic: "an",
      section: "an-enzymes",
      difficulty: "core",
      question: "Lentils (dal) are rich in protein. What does protease break protein down into?",
      options: ["Fatty acids and glycerol", "Sugars such as glucose", "Vitamins and minerals", "Amino acids"],
      answerIndex: 3,
      optionFeedback: [
        "Fatty acids and amino acids both have 'acids' in their names, so they're easy to confuse — but fatty acids and glycerol come from lipase digesting fats.",
        "Glucose is the best-known product of digestion, so it's a natural guess — but sugars come from carbohydrates like starch (digested by carbohydrase), not from protein.",
        "Lentils do contain vitamins and minerals, which makes this tempting — but they are separate nutrients that are already small enough to absorb; digesting protein doesn't produce them.",
        "Protease breaks the long protein chains into amino acids, which are small and soluble enough to be absorbed into the blood.",
      ],
      explanation:
        "Proteins are long chains of **amino acids** joined together. **Protease** breaks these chains apart — first in the **stomach**, then in the **small intestine** — releasing amino acids that are absorbed into the blood and used for **growth and repair**. Picture a protein as a bead necklace: protease cuts the string, and the loose beads are the amino acids.",
      hints: [
        "Proteins are long chains made from smaller building blocks. What are those building blocks called?",
        "Fatty acids and glycerol come from fats, and sugars come from carbohydrates.",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q10",
      topic: "an",
      section: "an-enzymes",
      difficulty: "core",
      question: "Cheese and paneer contain lipids (fats). When lipids are digested, what are they broken down into?",
      options: ["Fatty acids and glycerol", "Amino acids and glycerol", "Glucose and fatty acids", "Smaller droplets of fat"],
      answerIndex: 0,
      optionFeedback: [
        "Lipase breaks each lipid molecule into glycerol and fatty acids, which are small enough to be absorbed.",
        "Glycerol is right, and the word 'acids' makes this an easy mix-up — but amino acids come from digesting protein, not fat.",
        "Fatty acids are half of the answer, which makes this tempting — but glucose comes from digesting carbohydrates such as starch, not fat.",
        "Making smaller droplets is what bile does (emulsifying) — it breaks fat UP, but the droplets are still fat. Digestion by lipase breaks fat DOWN into new, smaller molecules.",
      ],
      explanation:
        "Each lipid molecule is made of **glycerol joined to three fatty acids**, so the enzyme **lipase** splits it into **fatty acids and glycerol** in the small intestine. Don't confuse this with **bile**: bile only breaks fat **up** into smaller droplets (emulsifying) — the droplets are still fat until lipase breaks them **down**. Memory trick: the products of fat digestion even have 'fat' in their name — **fat**ty acids (plus glycerol).",
      hints: [
        "A lipid molecule is made of two different kinds of smaller molecule joined together.",
        "Bile makes smaller droplets, but digestion makes brand-new, smaller molecules — and one of them has 'fat' in its name.",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "s2-q11",
      topic: "an",
      section: "an-enzymes",
      difficulty: "core",
      question: "Which statement about digestive enzymes is correct?",
      options: [
        "They are tiny living things that eat food molecules",
        "They get used up each time they break down food",
        "They are proteins that speed up chemical reactions",
        "They join small food molecules to make large ones",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Enzymes attack food molecules, so it's easy to imagine them as tiny creatures — but they are chemicals (proteins), and enzymes are not living things.",
        "It's easy to think an enzyme gets used up like fuel, but it comes out of each reaction unchanged and can be used again and again.",
        "Enzymes are proteins that act as biological catalysts, speeding up reactions such as breaking starch into sugars.",
        "Digestion is all about large and small molecules, so the direction is easy to muddle — but digestive enzymes break large, insoluble molecules into small, soluble ones.",
      ],
      explanation:
        "An **enzyme is a protein that catalyses (speeds up) a chemical reaction**. Digestive enzymes speed up the breakdown of large food molecules into small ones — for example, amylase turns starch into sugar. Remember three facts: enzymes are **made of protein**, they are **not living**, and they are **not used up**. Think of an enzyme as a pair of scissors: it cuts big molecules into small pieces, and it is still the same pair of scissors afterwards.",
      hints: [
        "Enzymes are made of one of the seven nutrients you have learned about.",
        "Think of an enzyme like a pair of scissors cutting paper. Are the scissors alive? Do they disappear after cutting?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s2-q12",
      topic: "an",
      section: "an-food-tests",
      difficulty: "core",
      question: "A student wants to test apple juice for sugar using Benedict's solution. What must she do, and what result shows that sugar is present?",
      options: [
        "Leave it at room temperature; it turns brick red",
        "Heat it in a hot water bath; it turns brick red",
        "Heat it in a hot water bath; it turns blue-black",
        "Heat it in a hot water bath; it turns purple",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Brick red is the right colour, but Benedict's solution only changes colour when it is heated — at room temperature it stays blue even if sugar is there.",
        "Benedict's must be heated in a hot water bath, and apple juice is full of sugar, so the blue solution turns brick red.",
        "Heating in a water bath is right, which makes this tempting — but blue-black is the iodine result for starch, not a Benedict's colour.",
        "Heating in a water bath is right, which makes this tempting — but purple (lilac) is the biuret result for protein, and the biuret test doesn't need heating.",
      ],
      explanation:
        "**Benedict's test for sugar:** mix the food with water, add blue Benedict's solution, then **heat it in a hot water bath** for a few minutes. If sugar (such as glucose) is present, the colour changes from **blue → green → yellow → orange → brick red** — the more sugar, the further along it goes, so brick red means lots of sugar. It is the only one of the four food tests that needs heating. Memory trick: **B**enedict's needs a **B**ath.",
      hints: [
        "Benedict's test is different from the other three food tests — it needs one extra step.",
        "Blue-black and purple are the positive colours for two other food tests.",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q13",
      topic: "an",
      section: "an-food-tests",
      difficulty: "core",
      question: "A student adds biuret reagent to some crushed beans. Which result shows that the beans contain protein?",
      options: [
        "It turns from blue to purple (lilac)",
        "It turns from blue to orange or brick red",
        "It stays the same blue colour as before",
        "It turns from blue to a dark blue-black",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Biuret reagent turns from blue to purple (lilac) when protein is present, and beans are a good source of protein.",
        "Benedict's and biuret both start blue, so they're easy to mix up — but orange or brick red is the Benedict's result for sugar, after heating.",
        "Biuret reagent starts blue, so 'blue' can look like a result — but no change means no protein was found, which is a negative result.",
        "Blue-black and purple are both dark colours, which is why they get mixed up — but blue-black is the iodine result for starch.",
      ],
      explanation:
        "**Biuret test for protein:** add biuret reagent (a mixture of potassium hydroxide and copper sulfate) to the food. It starts **blue**, and turns **purple / lilac** if protein is present — no heating needed. Lentils, beans, tofu, paneer and milk all give a purple result. Memory trick: **P**urple means **P**rotein.",
      hints: [
        "Biuret reagent starts off blue, and a positive result means the colour changes.",
        "Orange or brick red belongs to the sugar test, and blue-black belongs to the starch test.",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "s2-q14",
      topic: "an",
      section: "an-food-tests",
      difficulty: "core",
      question: "A student shakes a crushed food sample with ethanol, then pours the ethanol into a test tube of water. A milky white layer forms. Which nutrient does this show is present?",
      options: ["Starch", "Sugar (glucose)", "Protein", "Fat (lipid)"],
      answerIndex: 3,
      optionFeedback: [
        "Starch is a white powder, so a white result might seem to fit — but the starch test uses iodine solution, which turns blue-black.",
        "Sugar is one of the four nutrients you can test for, so it's a natural guess — but sugar is tested with Benedict's solution, which turns orange or brick red when heated, not milky white.",
        "Milk contains protein, so a 'milky' result might make you think of protein — but protein is tested with biuret reagent, which turns purple.",
        "Fat dissolves in ethanol, and when the ethanol is poured into water the fat forms tiny droplets that look milky white.",
      ],
      explanation:
        "**Emulsion test for fat (lipid):** shake the food with **ethanol**, then pour the ethanol into **water**. A **milky white (cloudy) layer** — an emulsion — means fat is present; if it stays clear, there is no fat. It works because fat dissolves in ethanol but not in water, so when the ethanol meets the water the fat comes out as tiny droplets that make it look cloudy. Memory trick: fatty foods make the water look like **full-fat milk**.",
      hints: [
        "This is the only food test that uses ethanol and water instead of a coloured reagent.",
        "The other three nutrients are tested with iodine, Benedict's solution and biuret reagent — so which one is left?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s2-q15",
      topic: "an",
      section: "an-nutrients",
      difficulty: "core",
      question: "Wholegrain bread, brown rice, beans and vegetables are good sources of fibre. Why is fibre important in your diet?",
      options: [
        "It is digested into sugars that give us slow-release energy",
        "It is absorbed into the blood and helps build new cells",
        "It keeps food and faeces moving and prevents constipation",
        "It neutralises stomach acid and so prevents indigestion",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Fibre is a type of carbohydrate, so it's tempting to think it gives energy — but our digestive enzymes cannot break it down, so it is never turned into sugars.",
        "Absorbing nutrients to build cells sounds like what healthy food does, but that's protein's job — fibre can't be digested, so it is never absorbed into the blood.",
        "Fibre can't be digested, so it adds bulk that the gut muscles can push along, keeping food and faeces moving and preventing constipation.",
        "Fibre is good for your gut, so it might seem to help with indigestion — but neutralising acid is what antacids (bases) do, and fibre is not a base.",
      ],
      explanation:
        "**Fibre cannot be digested** — our enzymes can't break it down, so it is never absorbed into the blood. Instead it passes all the way through the gut, giving the muscles something to push against, which **keeps food and faeces moving** and **prevents constipation**. That's why wholegrain bread, brown rice, beans, fruit and vegetables help you go to the toilet regularly. Memory trick: fibre is the gut's broom — it sweeps everything along.",
      hints: [
        "Can your digestive enzymes break fibre down, or does it stay as it is?",
        "Think about the problem someone gets if they don't eat enough fruit, vegetables or wholegrains.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s2-q16",
      topic: "an",
      section: "an-diet",
      difficulty: "core",
      question: "Which of these is the best definition of malnutrition?",
      options: [
        "Not eating enough food, so that the body becomes thin and underweight",
        "Eating too much or too little of some nutrients, causing ill health",
        "Not drinking enough water, so you feel tired and get headaches",
        "Getting ill from eating food that has gone off or is full of germs",
      ],
      answerIndex: 1,
      optionFeedback: [
        "This is one kind of malnutrition, so it's tempting — but it's too narrow. Eating too much of some nutrients, which can lead to obesity, is malnutrition too.",
        "Malnutrition means a poor, unbalanced diet — too much or too little of some nutrients — that leads to health problems.",
        "Water is important, which makes this tempting — but this describes dehydration, which has its own name. Malnutrition is about the balance of nutrients in your whole diet.",
        "'Mal' does mean 'bad', which makes this tempting — but getting ill from food that has gone off or has germs in it is food poisoning, not malnutrition.",
      ],
      explanation:
        "**Malnutrition** means a **poor, unbalanced diet that leads to health problems** — eating **too much or too little** of one or more nutrients. So a child who is very weak from too little protein is malnourished, but so is someone who becomes **obese** from eating too much fat and sugar. A **balanced diet** gives you all seven nutrients — carbohydrates, proteins, fats, vitamins, minerals, fibre and water — in the right amounts.",
      hints: [
        "Two of the options describe problems that have their own separate names.",
        "Could someone who is very overweight also have a poor, unbalanced diet?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s2-q17",
      topic: "an",
      section: "an-absorption",
      difficulty: "core",
      question: "The inside wall of the small intestine is covered in millions of tiny, finger-like villi. What is their job?",
      options: [
        "To make acid that kills the bacteria in our food",
        "To make bile, which breaks fat up into small droplets",
        "To grip the food and push it along the gut",
        "To give a very large surface area for absorption",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Acid is part of digestion, which makes this sound possible — but it is made in the stomach to kill bacteria. Villi are in the small intestine and don't make acid.",
        "Bile does work in the small intestine, which makes this tempting — but it is made in the liver, not by the villi.",
        "Their finger shape makes this tempting, but food is pushed along by muscles in the gut wall, not by the villi.",
        "Millions of villi give the small intestine a huge surface area, so digested food can be absorbed into the blood quickly.",
      ],
      explanation:
        "**Villi** are tiny finger-like projections lining the small intestine. Together they give it a **very large surface area**, so much more digested food (glucose, amino acids, fatty acids and glycerol) can be **absorbed into the blood** in the same time. Each villus also has walls just **one cell thick** and lots of **capillaries**, so absorption is fast. Think of a fluffy towel: its thousands of tiny loops give it a much bigger surface than a flat cloth, so it soaks up far more water.",
      hints: [
        "Villi are found in the part of the gut where digested food passes into the blood.",
        "Imagine flattening out all those tiny fingers — how much space would their surface cover?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q18",
      topic: "an",
      section: "an-system",
      difficulty: "core",
      question: "Why does the stomach contain hydrochloric acid?",
      options: [
        "To kill bacteria and give the right conditions for protease",
        "To digest starch into glucose so it can be used for energy",
        "To dissolve all the food so it can be absorbed in the stomach",
        "To emulsify fats by breaking them up into smaller droplets",
      ],
      answerIndex: 0,
      optionFeedback: [
        "The acid kills bacteria in food and makes the stomach acidic, which is the right condition for the stomach's protease to digest protein.",
        "Glucose and energy are linked to digestion, so this sounds reasonable — but starch is digested by carbohydrase (amylase) in the mouth and small intestine, not by acid.",
        "Acid sounds strong enough to dissolve food, but digestion is done by enzymes, and digested food is absorbed in the small intestine, not the stomach.",
        "Bile and stomach acid are both digestive juices, so they're easy to confuse — but emulsifying fats is bile's job, and bile is alkaline, the opposite of an acid.",
      ],
      explanation:
        "The stomach **churns** food and mixes it with **hydrochloric acid** and **protease**. The acid has two jobs: it **kills bacteria** that come in with your food, and it gives the **right (acidic) conditions** for stomach protease to start breaking protein down into amino acids. Later, alkaline **bile** helps neutralise this acid in the small intestine — a neat link to your Acids & Alkalis topic!",
      hints: [
        "Food isn't always perfectly clean. What harmful things could a strong acid destroy?",
        "Protein digestion starts in the stomach. What does the enzyme there need in order to work well?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s2-q19",
      topic: "an",
      section: "an-bile",
      difficulty: "core",
      question: "Bile is released into the small intestine. What does it do to fats?",
      options: [
        "It digests fats into fatty acids and glycerol",
        "It joins small fat droplets into larger drops",
        "It emulsifies fat into many small droplets",
        "It neutralises fats so they can be absorbed",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Bile is tempting here because it helps with fat — but this is what the enzyme lipase does. Bile is not an enzyme and doesn't break fat down chemically.",
        "Bile does change the size of fat drops, so this is close — but it's the wrong way round: bile splits big drops into lots of small ones; it doesn't join them together.",
        "Bile emulsifies fat: it breaks large fat droplets up into many small droplets, giving lipase a much bigger surface area to work on.",
        "Bile does neutralise something — the acid arriving from the stomach — but it doesn't neutralise fat. Its job with fat is to break it into small droplets.",
      ],
      explanation:
        "Bile (made in the liver, stored in the gall bladder) **emulsifies** fats: it breaks large fat droplets **up** into many **small droplets**, a bit like washing-up liquid breaking up grease on a plate. Bile is **not an enzyme**, so the fat is not chemically digested — it is still fat. But the small droplets have a much **bigger surface area**, so **lipase** can digest them into fatty acids and glycerol much faster. Memory trick: bile breaks fat **UP**; lipase breaks fat **DOWN**.",
      hints: [
        "Remember: bile is not an enzyme, so it can't break fat into new molecules.",
        "Think about what washing-up liquid does to the grease on an oily plate.",
      ],
      strategy: "Eliminate wrong options",
    },

    // ───────────────────────── CHALLENGE ─────────────────────────
    {
      id: "s2-q20",
      topic: "an",
      section: "an-absorption",
      difficulty: "challenge",
      question: "The small intestine is adapted to absorb digested food quickly. Which of these is NOT one of its adaptations?",
      options: [
        "Villi that give it a very large surface area",
        "Walls only one cell thick, so the distance is short",
        "Lots of capillaries, giving a good blood supply",
        "Thick walls that protect the blood vessels",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Villi might look as if they'd just get in the way, but they are a real adaptation — they give a huge surface area, so much more digested food can be absorbed at once.",
        "Thin walls might sound weak, but they are a real adaptation — digested food only has a very short distance to travel into the blood.",
        "Capillaries belong to the blood system, so they might not seem like part of the gut — but lots of them around the villi are a real adaptation, carrying absorbed food away quickly so more can be absorbed.",
        "Thick walls would make digested food travel further and slow absorption — the real walls are only one cell thick, so this is not an adaptation.",
      ],
      explanation:
        "The small intestine has three adaptations for fast absorption: **villi** give a **very large surface area**; the walls are **one cell thick**, so there is only a **short distance** for digested food to travel; and **lots of capillaries** give a **good blood supply** to carry the food away. Thick walls would do the opposite — a longer distance means slower absorption. Memory trick: remember the three S's — big **S**urface area, **S**hort distance, good blood **S**upply.",
      hints: [
        "Three of these options really do help absorption. Look for the one that would slow it down.",
        "Absorption is fastest when digested food only has a short distance to travel into the blood.",
        "How thick are the walls of the villi — many cells, or just one?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s2-q21",
      topic: "an",
      section: "an-enzymes",
      difficulty: "challenge",
      question: "A bowl of dal (lentil curry) is rich in protein. In which parts of the digestive system is this protein digested?",
      options: [
        "Mouth and small intestine",
        "Stomach and small intestine",
        "Small intestine only",
        "Stomach and large intestine",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Digestion does begin in the mouth, which makes this tempting — but chewing only breaks the dal into smaller pieces. Saliva contains amylase (for starch), not protease, so the protein isn't digested until it reaches the stomach.",
        "Protease made by the stomach starts protein digestion, and protease from the pancreas finishes it in the small intestine.",
        "This is the route for fat (lipase, helped by bile), which makes it easy to confuse — but protein digestion starts earlier, because the stomach makes its own protease.",
        "The stomach is right, which makes this tempting — but by the large intestine digestion is over; the large intestine absorbs water from undigested food.",
      ],
      explanation:
        "Each nutrient has its own digestion route:\n\n- **Starch:** mouth (amylase in saliva) and small intestine\n- **Protein:** stomach (protease, helped by the acid) and small intestine (protease from the pancreas)\n- **Fat:** small intestine only (lipase, helped by bile)\n\nThe large intestine doesn't digest food — it absorbs water. Memory trick: the stomach makes acid to help protease, so that's where protein digestion starts.",
      hints: [
        "Think about which digestive juices contain protease, and where they are made.",
        "The pancreas sends protease into the small intestine — but protease is also made by an organ that food reaches before the small intestine.",
        "Remember why the stomach contains acid: it gives the right conditions for one particular enzyme.",
      ],
      strategy: "Follow the food",
    },
    {
      id: "s2-q22",
      topic: "an",
      section: "an-nutrients",
      difficulty: "challenge",
      question: "Vitamins, minerals and water are absorbed into the blood without being digested. Why don't they need digesting?",
      options: [
        "They are already small and soluble enough to be absorbed",
        "Stomach acid breaks them down instead, so no enzymes are needed",
        "Cooking the food has already broken them down",
        "The body needs so little of them that it skips digestion",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Digestion is only needed to turn large insoluble molecules into small soluble ones, and vitamins, minerals and water are already small enough to pass into the blood.",
        "Stomach acid is strong, so it might seem able to break things down — but its jobs are killing bacteria and helping protease work, and these nutrients don't need breaking down at all.",
        "Cooking does soften food, which makes this tempting — but it doesn't digest it, and raw fruit and vegetables are full of vitamins that are absorbed without any cooking.",
        "We do need only small amounts of vitamins and minerals, which makes this tempting — but that isn't the reason, and we need lots of water, which isn't digested either.",
      ],
      explanation:
        "**Digestion** means breaking **large, insoluble** molecules (like starch, protein and fat) into **small, soluble** ones that can pass through the wall of the small intestine into the blood. **Vitamins, minerals and water are already small enough** to be absorbed as they are, so they don't need breaking down. Fibre is the opposite case: it can't be digested at all, so it is never absorbed. Rule of thumb: only big molecules need digesting.",
      hints: [
        "What is the whole point of digestion? Think about the school's definition.",
        "Compare a huge starch molecule with a tiny water molecule. Which one needs breaking down?",
        "If something can already pass into the blood as it is, does it need to be digested?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "s2-q23",
      topic: "an",
      section: "an-food-tests",
      difficulty: "challenge",
      question: "A student carries out all four food tests on an unknown food. Her results are shown in the table. Which nutrient or nutrients does the food contain?",
      table: {
        caption: "Food test results for the unknown food",
        headers: ["Food test", "Colour at the start", "Colour at the end"],
        rows: [
          ["Iodine solution", "Orange-brown", "Orange-brown"],
          ["Benedict's solution (heated)", "Blue", "Brick red"],
          ["Biuret reagent", "Blue", "Blue"],
          ["Ethanol, then water", "Clear", "Clear"],
        ],
      },
      options: ["Starch and sugar", "Protein only", "Sugar only", "Sugar and protein"],
      answerIndex: 2,
      optionFeedback: [
        "Orange-brown is a strong colour, so it can look like a result — but it's iodine's starting colour and it didn't change, so there is no starch.",
        "Benedict's and biuret both start blue, so they're easy to mix up — but brick red is the Benedict's result for sugar, and the biuret stayed blue, so there's no protein.",
        "Only Benedict's changed colour (blue to brick red), so the food contains sugar, while the other three tests stayed the same, showing no starch, protein or fat.",
        "Sugar is right, and biuret's blue can look like a result — but it didn't change. Biuret only shows protein if it turns purple (lilac).",
      ],
      explanation:
        "Read each row and ask: **did the colour change?** A food test is only positive if the colour changes: iodine → **blue-black** (starch), Benedict's → **green, yellow, orange or brick red** (sugar), biuret → **purple** (protein), ethanol then water → **milky white** (fat). Here only Benedict's changed, and brick red means **lots of sugar** — apple juice would give results like these. If the end colour is the same as the starting colour, the result is negative.",
      hints: [
        "For each test, compare the starting colour with the end colour. Which tests show a change?",
        "Remember the starting colours: iodine starts orange-brown, and Benedict's and biuret both start blue.",
        "Only one row shows a change. Which nutrient does that test detect?",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "s2-q24",
      topic: "an",
      section: "an-absorption",
      difficulty: "challenge",
      question: "Look at the diagram of the digestive system. Which letter labels the organ where digested food is absorbed into the blood?",
      figure: "digestive-lettered",
      options: ["D", "F", "G", "E"],
      answerIndex: 1,
      optionFeedback: [
        "D is the stomach. Food stays there for a long time, which makes it tempting — but it churns food with acid and protease; digested food is absorbed further along, in the small intestine.",
        "F is the small intestine, where millions of villi absorb digested food into the blood.",
        "G is the large intestine. It does absorb something, which makes it tempting — but it absorbs water from undigested food; the digested food has already been absorbed in the small intestine.",
        "E is the pancreas. It sits right beside the gut, but it makes enzymes and sends them into the small intestine — food never passes through it.",
      ],
      explanation:
        "Digested food — glucose, amino acids, fatty acids and glycerol — is absorbed into the blood in the **small intestine (F)**. It comes straight after the stomach and is lined with millions of **villi**, which give a very large surface area, with thin walls and lots of capillaries. Don't mix it up with the **large intestine (G)**, which comes after it and absorbs **water** from the undigested leftovers.",
      hints: [
        "First name the organ: where in the gut are the villi found?",
        "This organ comes straight after the stomach on the journey of food.",
        "Don't pick the large intestine (it absorbs water, not digested food) — the letter you want labels the organ just before it.",
      ],
      strategy: "Follow the food",
    },
    {
      id: "s2-q25",
      topic: "an",
      section: "an-system",
      difficulty: "challenge",
      question: "Which list shows the correct order in which food passes through the digestive system?",
      options: [
        "Mouth → oesophagus → stomach → liver → small intestine → large intestine → rectum → anus",
        "Mouth → oesophagus → stomach → large intestine → small intestine → rectum → anus",
        "Mouth → oesophagus → stomach → pancreas → small intestine → large intestine → rectum → anus",
        "Mouth → oesophagus → stomach → small intestine → large intestine → rectum → anus",
      ],
      answerIndex: 3,
      optionFeedback: [
        "The liver sits close to the stomach and sends bile into the small intestine, which makes it tempting — but food never passes through the liver itself.",
        "Both intestines are there, which makes this look right — but they're swapped: food reaches the small intestine first (to be digested and absorbed), then the large intestine (where water is absorbed).",
        "The pancreas sends enzymes into the small intestine, which makes it tempting — but food never passes through the pancreas itself.",
        "Food travels through one continuous tube: mouth, oesophagus, stomach, small intestine, large intestine, rectum, then out through the anus.",
      ],
      explanation:
        "Food passes through **one long tube**: **mouth → oesophagus → stomach → small intestine → large intestine → rectum → anus**. The **liver** (which makes bile, stored in the gall bladder) and the **pancreas** (which makes enzymes) are joined to this tube and send their juices into the small intestine, but food **never passes through them**. Memory trick: **M**y **O**ld **S**ister **S**ings **L**oudly, **R**ather **A**nnoyingly — Mouth, Oesophagus, Stomach, Small intestine, Large intestine, Rectum, Anus.",
      hints: [
        "Food travels along a single tube. Some organs only add juices to that tube — food doesn't go through them.",
        "Which organs make bile and enzymes but are not part of the food tube?",
        "Food must be digested and absorbed before the water is taken out of what's left.",
      ],
      strategy: "Follow the food",
    },
  ],
};
