import type { MCQ, QuestionSet } from "../types";

export const MCQ_SET_1: QuestionSet<MCQ> = {
  id: "mcq-1",
  title: "Set 1 · Acids & Alkalis",
  subtitle: "Every lesson on the cover sheet — warm-up to challenge",
  topic: "aa",
  questions: [
    // ───────────────────────────── WARM-UP ─────────────────────────────
    {
      id: "s1-q01",
      topic: "aa",
      section: "aa-everyday",
      difficulty: "warmup",
      question: "Lemons taste sour because they contain an acid. Which acid is it?",
      options: ["Ethanoic acid", "Hydrochloric acid", "Citric acid", "Carbonic acid"],
      answerIndex: 2,
      optionFeedback: [
        "Ethanoic acid is a real food acid, so it's a sensible guess — but it is the acid in vinegar, not in lemons.",
        "Hydrochloric acid is the acid name you hear most in the lab (it's in your stomach too), but it isn't the acid in fruit.",
        "Lemons and other citrus fruits contain citric acid, which gives them their sharp, sour taste.",
        "Carbonic acid is a food acid too, but it is the one in fizzy drinks, not in lemons.",
      ],
      explanation:
        "Many foods and drinks contain weak acids, which is why they taste **sour**. Learn the school's four kitchen acids: **lemons – citric acid**, **vinegar – ethanoic acid**, **fizzy drinks – carbonic acid** and **vitamin C – ascorbic acid**. Memory trick: **citric** sounds like **citrus**, the fruit family that lemons, limes and oranges belong to.",
      hints: ["Think about where you meet each acid: which one is in vinegar, which is in fizzy drinks, and which is a lab acid?"],
      strategy: "Recall the keyword",
    },
    {
      id: "s1-q02",
      topic: "aa",
      section: "aa-indicators",
      difficulty: "warmup",
      question: "A student dips a strip of blue litmus paper into dilute sulfuric acid. What happens to the litmus paper?",
      options: ["It turns red", "It stays blue", "It turns green", "It turns orange"],
      answerIndex: 0,
      optionFeedback: [
        "Acids turn blue litmus paper red, and sulfuric acid is an acid.",
        "Blue litmus does stay blue in alkalis and neutral solutions, which makes this easy to mix up — but in an acid it turns red.",
        "Green is the universal indicator colour for a neutral solution. Litmus only has two colours, red and blue, so it can never turn green.",
        "Universal indicator can turn orange in some acids, but litmus is a different indicator with only two colours: red and blue.",
      ],
      explanation:
        "Litmus paper has only **two colours**, red and blue. **Acids turn blue litmus red; alkalis turn red litmus blue**, and in a neutral solution neither paper changes colour. Memory trick: in an acid, litmus always **ends up red**; in an alkali, it always **ends up blue**.",
      hints: ["Litmus paper can only ever be one of two colours. Which of those two colours goes with acids?"],
      strategy: "Recall the keyword",
    },
    {
      id: "s1-q03",
      topic: "aa",
      section: "aa-ph",
      difficulty: "warmup",
      question: "A solution is tested and found to have a pH of exactly 7. How would you describe it?",
      options: ["Weakly acidic", "Weakly alkaline", "Strongly alkaline", "Neutral"],
      answerIndex: 3,
      optionFeedback: [
        "pH 7 sits right next to the weak acids (pH 5–6), but acidic means BELOW 7 — and 7 is not below 7.",
        "Weakly alkaline solutions are just ABOVE 7, like pH 8. pH 7 itself is the exact middle of the scale.",
        "Strongly alkaline solutions are near the top of the scale (about pH 11–14) and turn universal indicator purple. pH 7 is the middle, not the top.",
        "pH 7 is exactly in the middle of the scale, so the solution is neither acidic nor alkaline — it is neutral.",
      ],
      explanation:
        "The pH scale runs from 0 to 14: **below 7 is acidic, exactly 7 is neutral, above 7 is alkaline**. A neutral solution, such as pure water, turns universal indicator **green**. Memory trick: think of 7 as the **balance point** of a see-saw, with the acids on the low-number side and the alkalis on the high-number side.",
      hints: ["Where does 7 sit on a pH scale that runs from 0 to 14?"],
      strategy: "Use the pH scale",
    },
    {
      id: "s1-q04",
      topic: "aa",
      section: "aa-everyday",
      difficulty: "warmup",
      question: "Which of these is a common laboratory acid?",
      options: ["Sodium hydroxide", "Hydrochloric acid", "Sodium chloride", "Calcium hydroxide"],
      answerIndex: 1,
      optionFeedback: [
        "Sodium hydroxide is a very common lab chemical, but it is an alkali, not an acid — the '-hydroxide' ending is the clue.",
        "Hydrochloric acid is one of the three common lab acids, along with sulfuric acid and nitric acid.",
        "The 'chlor' looks like part of hydrochloric acid, but sodium chloride is table salt — the salt made when sodium hydroxide neutralises hydrochloric acid.",
        "Calcium hydroxide is a base (farmers spread it on fields as lime), so it neutralises acids rather than being one.",
      ],
      explanation:
        "The three common **laboratory acids** are **hydrochloric acid, sulfuric acid and nitric acid**, and they can be dilute or concentrated. Use the endings to sort the others: names ending in **'-hydroxide'** (sodium hydroxide, calcium hydroxide) are bases that neutralise acids, and **sodium chloride** is a salt. Memory trick for the lab acids: **H**ydrochloric, **S**ulfuric, **N**itric — '**H**ave **S**ome **N**achos'.",
      hints: ["Two of these names end in '-hydroxide'. What type of substance does that ending tell you about?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s1-q05",
      topic: "aa",
      section: "aa-hazards",
      difficulty: "warmup",
      question: "A bottle of concentrated sulfuric acid has the corrosive hazard symbol on it. What is this symbol warning you about?",
      options: [
        "It can destroy skin, eyes and metals",
        "It catches fire easily near a flame",
        "It may cause mild skin irritation",
        "It is toxic and can kill in small amounts",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Corrosive substances attack and destroy what they touch — skin, eyes and even metals.",
        "Fire is a common lab danger, but catching fire is what the flame (flammable) symbol warns about. The corrosive symbol is about a substance eating away at things.",
        "Irritant and corrosive both affect skin, so they're easy to mix up — but mild irritation is the exclamation mark (irritant) symbol, often found on dilute acids. Corrosive is far more serious.",
        "Both symbols mean danger, but the skull and crossbones (toxic) warns about poisons that can kill in small amounts. The corrosive symbol is about burning and destroying on contact.",
      ],
      explanation:
        "A **corrosive** substance can destroy metals, stonework and living tissue such as **skin and eyes** — the symbol shows liquid dripping onto a hand and a piece of metal. **Concentrated** acids and alkalis usually carry the corrosive symbol, while **dilute** ones often carry the **irritant** (exclamation mark) symbol instead. Memory trick: corrosive comes from **'corrode'**, which means to eat away.",
      hints: ["Imagine a strong acid splashing onto your hand or onto a metal tap. What would it do?"],
      strategy: "Recall the keyword",
    },
    {
      id: "s1-q06",
      topic: "aa",
      section: "aa-neutralisation",
      difficulty: "warmup",
      question: "Which is the general word equation for neutralisation?",
      options: [
        "acid + alkali → base + water",
        "salt + water → acid + alkali",
        "acid + alkali → salt + water",
        "acid + water → salt + alkali",
      ],
      answerIndex: 2,
      optionFeedback: [
        "'Base' is a tempting word, but a base is what you ADD to neutralise an acid (an alkali is a soluble base). The new substance made is a salt.",
        "These are the right four words, but backwards — the acid and alkali are what you start with, so they go on the LEFT of the arrow.",
        "An acid and an alkali react together to make a salt and water — the general equation for neutralisation.",
        "Adding water to an acid only dilutes it, so it is still an acid. You need an alkali to neutralise it, and water is a product, not a reactant.",
      ],
      explanation:
        "**Neutralisation** is the reaction between an acid and an alkali: **acid + alkali → salt + water**. The **reactants** (acid and alkali) go on the left of the arrow and the **products** (salt and water) go on the right. Memory trick: neutralising an acid with an alkali gives you **salty water** — a salt dissolved in water.",
      hints: ["What two substances do you start with, and what two new substances are made? Which side of the arrow does each pair go on?"],
      strategy: "Recall the keyword",
    },
    {
      id: "s1-q07",
      topic: "aa",
      section: "aa-salts",
      difficulty: "warmup",
      question: "Salts made from hydrochloric acid all have the same ending to their name. What are they called?",
      options: ["Chlorates", "Hydroxides", "Chlorines", "Chlorides"],
      answerIndex: 3,
      optionFeedback: [
        "Easy slip — salts from sulfuric and nitric acid end in '-ate' (sulfate, nitrate). Hydrochloric acid is the odd one out: its salts end in '-ide'.",
        "Hydroxides like sodium hydroxide are the alkalis that react WITH the acid. The salt that is made gets a new name from the acid.",
        "Chlorine is the name of the element, but in a salt the ending changes: it's sodium chloride, not 'sodium chlorine'.",
        "Hydrochloric acid makes chlorides — for example, sodium hydroxide + hydrochloric acid → sodium chloride + water.",
      ],
      explanation:
        "Each acid gives its salts a family name: **hydrochloric acid → chloride**, **sulfuric acid → sulfate**, **nitric acid → nitrate**. The first word of the salt comes from the metal in the alkali, so potassium hydroxide + hydrochloric acid → **potassium chloride** + water. Memory trick: hydro**chlor**ic → **chlor**ide — keep the 'chlor' and swap the ending for '-ide'.",
      hints: ["Think of the most famous salt of all — the table salt you sprinkle on chips. What is its chemical name?"],
      strategy: "Name the salt (metal first, acid second)",
    },

    // ─────────────────────────────── CORE ───────────────────────────────
    {
      id: "s1-q08",
      topic: "aa",
      section: "aa-ph",
      difficulty: "core",
      question: "A few drops of universal indicator are added to some drain cleaner, and it turns purple. What is its approximate pH, and how would you describe it?",
      options: [
        "About pH 1 — strongly acidic",
        "About pH 14 — strongly alkaline",
        "About pH 8 — weakly alkaline",
        "About pH 14 — strongly acidic",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Strong acids are dangerous too, so this is tempting — but they turn universal indicator red. Purple is at the opposite end of the scale.",
        "Purple is the colour at the very top of the pH scale, so the drain cleaner is strongly alkaline, at about pH 14.",
        "Alkaline is right, but pH 8 is only weakly alkaline and would turn universal indicator blue. Purple means much more strongly alkaline.",
        "The number is right but the description is backwards: a pH above 7 is alkaline, and the higher the number, the more alkaline it is.",
      ],
      explanation:
        "Universal indicator colours follow the pH scale: **red (strongly acidic) → orange → yellow → green (neutral, pH 7) → blue → purple (strongly alkaline)**. Purple is the top band of the scale (about pH 11–14), so it means strongly alkaline. Many drain cleaners contain **caustic soda (sodium hydroxide)**, one of the most dangerous alkalis in the home, which is why they carry the **corrosive** symbol. Memory trick: **R**ed is **R**eally acidic; **P**urple is **P**owerfully alkaline.",
      hints: [
        "Picture the universal indicator colour chart, with red at one end and purple at the other. Which end is purple?",
        "The further a colour is from green, the more strongly acidic or alkaline the solution. Is purple next to green, or right at the end?",
      ],
      strategy: "Use the pH scale",
    },
    {
      id: "s1-q09",
      topic: "aa",
      section: "aa-ph",
      difficulty: "core",
      question: "Four solutions are tested and their pH values are recorded. Which pH value shows the most acidic solution?",
      options: ["6", "9", "1", "4"],
      answerIndex: 2,
      optionFeedback: [
        "6 is the biggest of the acidic numbers here, which can make it feel like 'the most' — but it is only weakly acidic, just below neutral.",
        "pH 9 is above 7, so it is alkaline, not acidic at all. A bigger pH number does not mean more acid.",
        "pH 1 is the furthest below 7, so it is the most acidic — it would turn universal indicator red.",
        "pH 4 is acidic, but pH 1 is even further below 7, so pH 1 is more acidic.",
      ],
      explanation:
        "On the pH scale, **the lower the number, the more acidic** the solution, and the higher the number, the more alkaline. pH 1, 4 and 6 are all acidic, but **pH 1** is furthest from neutral (7), so it is the most acidic: universal indicator would be **red** at pH 1, **orange** at pH 4 and **yellow** at pH 6. Memory trick: think of 7 as home — the further **down** you go from 7, the more acidic; the further **up**, the more alkaline.",
      hints: [
        "First, which of these values are acidic at all? Acidic means below which number?",
        "Of the acidic values, which one is furthest away from neutral?",
      ],
      strategy: "Consider the extremes",
    },
    {
      id: "s1-q10",
      topic: "aa",
      section: "aa-indicators",
      difficulty: "core",
      question: "A student dips red litmus paper into a colourless solution, and the paper stays red. What can the student conclude?",
      options: [
        "It must be acidic",
        "It could be alkaline or neutral",
        "It must be neutral",
        "It could be acidic or neutral",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Acids do leave red litmus red — but so do neutral solutions, like pure water. 'Stays red' isn't enough to prove it's an acid.",
        "This mixes up the two papers: alkalis turn red litmus BLUE, so if it stayed red, the solution can't be alkaline.",
        "A neutral solution would leave red litmus red — but so would an acid, so 'no change' doesn't prove it's neutral.",
        "Red litmus stays red in acids and in neutral solutions and only turns blue in alkalis, so all you know is that it isn't alkaline.",
      ],
      explanation:
        "Red litmus has only one job: it **turns blue in an alkali**. In an acid it stays red, and in a neutral solution it also stays red — so 'stays red' only tells you the solution is **not alkaline**. To find out more, test with **blue litmus** (turns red in an acid, stays blue if neutral) or, better still, **universal indicator**, which gives the pH.",
      hints: [
        "What is the ONLY kind of solution that makes red litmus change colour?",
        "List every kind of solution that would leave red litmus exactly as it was.",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s1-q11",
      topic: "aa",
      section: "aa-indicators",
      difficulty: "core",
      question: "Which method would make a red cabbage indicator that you could use to test different solutions?",
      options: [
        "Chop, soak in hot water, filter, keep the coloured liquid",
        "Chop, soak in hot water, filter, keep the solid in the filter paper",
        "Chop, soak in hot water, evaporate all the water, keep the crystals",
        "Chop, soak in hot water, add alkali until green, keep the liquid",
      ],
      answerIndex: 0,
      optionFeedback: [
        "The purple dye dissolves into the hot water, so the coloured liquid that passes through the filter paper is your indicator.",
        "The cabbage looks like the important part, but the dye has dissolved into the water and passed through the filter paper. The soggy cabbage left behind has lost most of its colour.",
        "Evaporating is how you get solid salt from a salt solution. For an indicator you keep the coloured liquid, so you can add a few drops of it to each solution.",
        "'Add alkali until green' is a step from making a neutral solution, not an indicator. Adding alkali would change the indicator's colour before you even start testing.",
      ],
      explanation:
        "To make red cabbage indicator: **chop** the cabbage (a bigger surface area lets more dye out), **soak it in hot water** so the purple dye dissolves, then **filter** out the bits of cabbage. The **coloured liquid** that passes through the filter paper is your indicator. It turns **red/pink in acids**, stays **purple when neutral** and turns **green/yellow in alkalis**, so you can use it to sort solutions.",
      hints: [
        "When you soak chopped cabbage in hot water, where does the purple colour end up?",
        "Filtering separates a liquid from bits of solid. Which of the two holds the dye?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s1-q12",
      topic: "aa",
      section: "aa-hazards",
      difficulty: "core",
      question: "Why is dilute hydrochloric acid less hazardous than concentrated hydrochloric acid?",
      options: [
        "The water has neutralised some of the acid particles",
        "There are fewer acid particles in the same volume",
        "Each acid particle has shrunk to a smaller size",
        "Its pH has risen above 7, so it is now alkaline",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Water is neutral, so it's easy to think it cancels out the acid — but water can't neutralise an acid. It just spreads the same acid particles out.",
        "Dilute means fewer acid particles in each cm³, so fewer of them can react with your skin at once — less harmful, though still an acid.",
        "It can look as if the acid has become 'smaller', but particles don't change size when you add water. They're the same particles — there are just fewer in each cm³.",
        "Diluting does make the pH rise towards 7, but it can never go above 7. A dilute acid is still an acid.",
      ],
      explanation:
        "A **concentrated** acid has lots of acid particles dissolved in a small amount of water; a **dilute** acid has had water added, so there are **fewer acid particles in the same volume**. Fewer particles means less damage if it touches you, so dilute acids are **less hazardous** and often carry the **irritant** (exclamation mark) symbol instead of the corrosive one. Diluting is a good way to **reduce the risk**, but the solution is still an acid with a pH below 7.",
      hints: [
        "Think about what is actually in the bottle: acid particles and water particles. What changes when you add more water?",
        "Does adding water change the acid particles themselves, or just how spread out they are?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "s1-q13",
      topic: "aa",
      section: "aa-hazards",
      difficulty: "core",
      question: "In a risk assessment for an acid experiment, which of these is a PRECAUTION (not a hazard or a risk)?",
      options: [
        "Concentrated acid that can burn your skin",
        "The chance of acid splashing into an eye",
        "Wearing eye protection when pouring acid",
        "A cracked beaker with sharp, jagged edges",
      ],
      answerIndex: 2,
      optionFeedback: [
        "It sounds like a safety warning, but this is a hazard — something that could cause harm. A precaution is an action you take to make that harm less likely.",
        "This is a risk — the chance that a hazard actually causes harm. It mentions eyes, so it sounds like safety advice, but nobody is DOING anything.",
        "Wearing eye protection is an action that reduces the risk of acid harming your eyes, so it is a precaution.",
        "This is a hazard, because the sharp edges could cut you. A precaution would be something you do about it, like swapping it for an undamaged beaker.",
      ],
      explanation:
        "Three words, three different jobs: a **hazard** is something that could cause harm (corrosive acid, broken glass); a **risk** is the **chance** that the hazard actually causes harm; a **precaution** is an **action** you take to reduce the risk (wearing eye protection, using a dilute acid instead of a concentrated one). Memory trick: **H**azard = what could **H**urt you, **R**isk = how likely it is (the **R**oll of the dice), **P**recaution = how you **P**rotect yourself.",
      hints: [
        "A hazard is something that could cause harm, and a risk is the chance of harm happening. What does a precaution mean?",
        "A precaution is something a person actually does. Which option describes an action?",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "s1-q14",
      topic: "aa",
      section: "aa-everyday",
      difficulty: "core",
      question: "Which of these is the correct definition of an alkali?",
      options: [
        "A base that dissolves in water",
        "A base that does not dissolve in water",
        "Any base, whether it dissolves or not",
        "A substance that turns blue litmus red",
      ],
      answerIndex: 0,
      optionFeedback: [
        "This is the school's definition: an alkali is a soluble base — a base that dissolves in water.",
        "Easy to swap round! Many bases don't dissolve, but only the ones that DO dissolve in water are called alkalis.",
        "Every alkali is a base, so it's tempting to think it works the other way too — but copper oxide is a base that doesn't dissolve in water, so it isn't an alkali.",
        "It's easy to swap the litmus rules, but turning blue litmus red is what an acid does. An alkali turns red litmus blue.",
      ],
      explanation:
        "A **base** is any substance that neutralises an acid — metal oxides and metal hydroxides are bases. If a base **dissolves in water**, we also call it an **alkali**, so every alkali is a base but not every base is an alkali (sodium hydroxide is an alkali; copper oxide is an insoluble base). Memory trick: picture **bases** as a big family and **alkalis** as the members who can swim — they dissolve in water.",
      hints: [
        "Alkalis belong to a bigger family of substances that neutralise acids. What is that family called?",
        "Copper oxide neutralises acids but is NOT an alkali. What can sodium hydroxide do in water that copper oxide can't?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s1-q15",
      topic: "aa",
      section: "aa-everyday",
      difficulty: "core",
      question: "Which of these household products contains a strong, corrosive alkali?",
      options: ["Vinegar", "Lemon juice", "Fizzy drink", "Oven cleaner"],
      answerIndex: 3,
      optionFeedback: [
        "Vinegar has a strong smell, but it contains ethanoic acid — a weak acid that is safe to eat, not an alkali.",
        "Lemon juice can sting a cut, which makes it seem harsh, but it contains citric acid — it's a weak acid, not an alkali.",
        "Fizzy drinks can damage teeth, so they might seem harsh — but that's because they're acidic (carbonic acid), not alkaline.",
        "Oven cleaner contains a very strong alkali (often sodium hydroxide), which is corrosive — you need gloves and eye protection to use it.",
      ],
      explanation:
        "Many cleaning products contain **alkalis** — bleach, washing powder and oven cleaner. **Soap and washing-up liquid** are mild alkalis, but **oven cleaner** and **caustic soda** (used to unblock drains) are very strong, **corrosive** alkalis — the most dangerous alkalis in the home. The other three are foods and drinks containing weak acids: vinegar (ethanoic), lemon juice (citric) and fizzy drinks (carbonic). Memory trick: **sour foods → acids; many cleaning products → alkalis**.",
      hints: [
        "Three of these are things people eat or drink. What do sour-tasting foods and drinks usually contain?",
        "Which of these products would come with a warning to wear gloves?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s1-q16",
      topic: "aa",
      section: "aa-salts",
      difficulty: "core",
      question: "Complete the word equation: sodium hydroxide + sulfuric acid → ? + water. Which salt is made?",
      options: ["Sodium sulfide", "Sodium sulfate", "Sodium chloride", "Sulfur hydroxide"],
      answerIndex: 1,
      optionFeedback: [
        "Sodium is right, but salts from sulfuric acid end in '-ate', not '-ide'. Only hydrochloric acid gives an '-ide' salt (chloride).",
        "Sodium comes from sodium hydroxide, and sulfuric acid always makes sulfates — so the salt is sodium sulfate.",
        "Sodium chloride is the most famous salt, so it's tempting — but you'd need hydrochloric acid to make a chloride.",
        "This takes the wrong part from each reactant. The salt keeps the METAL from the alkali (sodium) and gets its second name from the acid (sulfate).",
      ],
      explanation:
        "To name a salt, the **first word is the metal from the alkali** and the **second word comes from the acid**: hydrochloric → chloride, sulfuric → sulfate, nitric → nitrate. So **sodium hydroxide + sulfuric acid → sodium sulfate + water**; the hydroxide part isn't in the salt because it joins with hydrogen from the acid to make the water. Memory trick: **sulf**uric → **sulf**ate and **nitr**ic → **nitr**ate — same start, '-ate' ending.",
      hints: [
        "The first word of the salt comes from the alkali. Which part of 'sodium hydroxide' is the metal?",
        "Salts from hydrochloric acid end in '-ide'. What ending do salts from sulfuric acid have?",
      ],
      strategy: "Name the salt (metal first, acid second)",
    },
    {
      id: "s1-q17",
      topic: "aa",
      section: "aa-salts",
      difficulty: "core",
      question: "Look at this word equation: potassium hydroxide + nitric acid → potassium nitrate + water. Which substances are the products?",
      options: [
        "Potassium nitrate and water",
        "Potassium hydroxide and nitric acid",
        "Potassium nitrate only",
        "Water only",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Products are the new substances made, written to the right of the arrow — here, potassium nitrate and water.",
        "These are written first, so they can look like the answer — but they are the reactants, the substances you start with, on the LEFT of the arrow.",
        "The salt is the 'interesting' new substance, so it's easy to forget the water — but everything to the right of the arrow is a product.",
        "It's easy to think neutralisation just 'turns acid into water', but the salt, potassium nitrate, is a product too.",
      ],
      explanation:
        "A word equation reads **reactants → products**. The **reactants** (potassium hydroxide and nitric acid) are on the **left** and get used up; the **products** (potassium nitrate and water) are on the **right** and are the new substances made. Neutralisation always makes **two** products: a salt and water. Memory trick: read the arrow as **'makes'** — potassium hydroxide and nitric acid MAKE potassium nitrate and water.",
      hints: [
        "In a word equation, which side of the arrow shows what you START with, and which side shows what is MADE?",
        "Products are the new substances made in a reaction. How many substances are written after the arrow?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s1-q18",
      topic: "aa",
      section: "aa-neutralisation",
      difficulty: "core",
      question: "After neutralising an acid with an alkali, you have a neutral salt solution. How can you get solid salt from it?",
      options: [
        "Filter it and keep the salt left on the filter paper",
        "Leave it to settle so the salt sinks to the bottom",
        "Heat it to evaporate the water and leave the salt",
        "Add more alkali until the salt comes out as a solid",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Filtering does separate solids, so it's tempting — but only solids that are NOT dissolved. The salt is dissolved, so it passes straight through with the water.",
        "Sand or mud in water would settle like this, but dissolved salt is spread evenly through the water and never sinks out on its own.",
        "Heating the solution (in an evaporating basin) evaporates the water, and the dissolved salt is left behind as solid crystals.",
        "It might seem that adding more reactant makes more salt appear, but extra alkali would just make the solution alkaline again (pH above 7) — and the salt would still be dissolved.",
      ],
      explanation:
        "When the acid and alkali have exactly neutralised each other, the salt is **dissolved** in the water, so filtering won't separate it. To get it back as a solid, **evaporate the water**: heat the solution gently in an **evaporating basin** (or leave it somewhere warm) and **salt crystals** are left behind. Memory trick: **W**ater **W**anders off, **S**alt **S**tays.",
      hints: [
        "Can you see bits of salt floating in the solution, or is the salt dissolved?",
        "If the salt is dissolved, which substance do you need to get rid of to leave the salt behind?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "s1-q19",
      topic: "aa",
      section: "aa-uses",
      difficulty: "core",
      question: "How does an antacid tablet relieve indigestion?",
      options: [
        "It is an acid that cancels out alkali in the stomach",
        "It dilutes the stomach acid until it becomes neutral",
        "It kills the bacteria in the stomach that cause the pain",
        "It is a base that neutralises excess hydrochloric acid",
      ],
      answerIndex: 3,
      optionFeedback: [
        "The name can make it sound like an acid, but 'antacid' means ANTI-acid. The stomach contains hydrochloric acid, not alkali, so a base is needed.",
        "Making the acid weaker sounds sensible, but adding water only dilutes an acid — it stays acidic. An antacid works by a chemical reaction: neutralisation.",
        "Stomach acid really does kill bacteria, so this sounds familiar — but an antacid doesn't target bacteria; it neutralises the extra acid.",
        "Indigestion happens when there is too much hydrochloric acid in the stomach, and the base in the antacid neutralises the excess, making a salt and water.",
      ],
      explanation:
        "Your stomach makes **hydrochloric acid**, which kills bacteria and gives the right conditions for the enzymes that digest protein — but too much of it causes **indigestion**. An **antacid** ('anti-acid') contains a **base**, such as magnesium hydroxide, which **neutralises the excess acid** to make a salt and water. Memory trick: **ant-acid = ANTI-acid** — it fights acid by neutralising it.",
      hints: [
        "Split the word 'antacid' into two parts. What does 'anti' mean?",
        "What kind of substance reacts with an acid and neutralises it?",
      ],
      strategy: "Apply it to a new situation",
    },

    // ───────────────────────────── CHALLENGE ─────────────────────────────
    {
      id: "s1-q20",
      topic: "aa",
      section: "aa-ph",
      difficulty: "challenge",
      question: "A beaker of acid has a pH of 2. A student adds a large amount of water to it and stirs. What happens to the pH?",
      options: [
        "It rises to 7, because water neutralises the acid",
        "It rises towards 7 but stays below 7",
        "It rises above 7, so it becomes alkaline",
        "It stays at 2, as the same acid particles are there",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Water is neutral, so it's tempting to think enough of it makes the acid neutral. But water can't neutralise an acid — the acid particles are still there, just spread out, so the solution stays slightly acidic.",
        "The acid particles are spread through more water, so the solution is less acidic and its pH rises towards 7 — but it is still an acid, so it stays below 7.",
        "Lots of water feels like it should 'flip' the solution, but water contains nothing alkaline, so diluting can never turn an acid into an alkali. The pH creeps up towards 7 but never goes above it.",
        "It's true that no acid particles are removed — but they're now spread through a much bigger volume. Fewer acid particles in each cm³ means less acidic, so the pH goes up.",
      ],
      explanation:
        "pH depends on how **concentrated** the acid is — how many acid particles there are in each cm³, not the total number. Adding water spreads the same particles through a bigger volume, so the solution becomes **less acidic** and its **pH rises towards 7** (from 2 to 3 or 4, say). But water can't neutralise an acid, so the pH **stays below 7** — it never becomes neutral or alkaline. It works the other way for alkalis: diluting lowers their pH towards 7, but never below it.",
      hints: [
        "Does adding water add or remove any acid particles — or does it just spread them out?",
        "If the acid particles are more spread out, is the solution more or less acidic? Which way does the pH number move?",
        "Only a base or alkali can neutralise an acid. Water is neither — so can the solution ever stop being acidic?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "s1-q21",
      topic: "aa",
      section: "aa-neutralisation",
      difficulty: "challenge",
      question: "A few drops of universal indicator are added to a beaker of dilute hydrochloric acid. Sodium hydroxide solution is then added slowly, with stirring, until the solution is exactly neutral. Which sequence of colours is seen?",
      options: [
        "Red → orange → yellow → green",
        "Purple → blue → green",
        "Red → orange → yellow → green → blue",
        "Green → yellow → orange → red",
      ],
      answerIndex: 0,
      optionFeedback: [
        "The acid starts red; as the alkali neutralises it, the pH rises through orange and yellow, and you stop at green (pH 7).",
        "This is what you'd see if you added acid to an alkali. Here the beaker starts with ACID, so the indicator begins red, not purple.",
        "So close — but blue means you've added too much alkali and gone past neutral (above pH 7). You should stop as soon as it turns green.",
        "This is backwards: adding an alkali makes the pH go UP, so the colours move from red towards green — not from green towards red.",
      ],
      explanation:
        "The beaker starts with **acid**, so the indicator is **red**. Each bit of alkali neutralises some of the acid, so the **pH rises**: red → **orange** → **yellow** → **green** at pH 7, and any more alkali would carry on to **blue** and **purple**. Near the end the colour changes quickly, which is why you add the alkali **drop by drop**. Memory trick: universal indicator colours run in **rainbow order** (red, orange, yellow, green, blue, indigo/violet) from pH 0 up to pH 14.",
      hints: [
        "What colour is universal indicator in the acid before any alkali is added?",
        "As alkali is added, does the pH go up or down? Which way does that move you along the colour chart?",
        "You must stop when the solution is exactly neutral. What colour is pH 7 — and should you go past it?",
      ],
      strategy: "Use the pH scale",
    },
    {
      id: "s1-q22",
      topic: "aa",
      section: "aa-salts",
      difficulty: "challenge",
      question: "Work backwards: a neutralisation reaction made calcium nitrate and water. Which two reactants were used?",
      options: [
        "Calcium hydroxide + sulfuric acid",
        "Sodium hydroxide + nitric acid",
        "Calcium hydroxide + nitric acid",
        "Sodium hydroxide + hydrochloric acid",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Sulfuric acid salts end in '-ate' too, so it's an easy mix-up — but they are sulfates. This pair would make calcium sulfate.",
        "Nitric acid is right, but sodium hydroxide would make sodium nitrate. The first word of the salt (calcium) tells you the metal in the alkali.",
        "Calcium comes from calcium hydroxide and 'nitrate' comes from nitric acid: calcium hydroxide + nitric acid → calcium nitrate + water.",
        "This is the classic neutralisation many people learn first, but it makes sodium chloride — neither part matches calcium nitrate.",
      ],
      explanation:
        "Work backwards from the salt's two names. The **first word gives the metal in the alkali** (calcium → calcium hydroxide) and the **second word gives the acid** (nitrate → nitric acid; sulfate → sulfuric acid; chloride → hydrochloric acid). So **calcium hydroxide + nitric acid → calcium nitrate + water** — always check your answer by reading the equation forwards.",
      hints: [
        "A salt's name has two parts. Which reactant gives the first part, and which gives the second?",
        "Which metal is in the salt — and which alkali contains that metal?",
        "Which acid makes salts whose names end in 'nitrate'?",
      ],
      strategy: "Work backwards",
    },
    {
      id: "s1-q23",
      topic: "aa",
      section: "aa-indicators",
      difficulty: "challenge",
      question: "Litmus and universal indicator can both be used to test solutions. Why is universal indicator usually more useful?",
      options: [
        "It can tell acids from alkalis, but litmus cannot",
        "It shows exactly which acid or alkali is in the solution",
        "It works on alkalis, but litmus only works on acids",
        "It shows the pH — how acidic or alkaline a solution is",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Universal indicator can tell acids from alkalis, but so can litmus: acids turn blue litmus red and alkalis turn red litmus blue. So this isn't the advantage.",
        "It would be handy if an indicator could name the substance, but it only shows how acidic or alkaline it is. Two different acids with the same pH give exactly the same colour.",
        "People often talk about 'the litmus test for acids', but litmus works for both: red litmus turns blue in alkalis. The real difference is how much detail universal indicator gives.",
        "Universal indicator has a range of colours that match pH values, so it tells you HOW acidic or alkaline a solution is, not just which one it is.",
      ],
      explanation:
        "Litmus has just two colours, so it can only answer a **yes/no question**: acid or alkali? **Universal indicator** is a mixture of dyes with a whole range of colours, one for each part of the **pH scale**, so it also tells you **how strongly** acidic or alkaline a solution is — pH 1 (red) is much more acidic than pH 4 (orange), even though blue litmus turns red in both. That makes it far better for comparing solutions and for spotting when a solution is exactly neutral (green).",
      hints: [
        "How many different colours can litmus paper show? How many can universal indicator show?",
        "Would blue litmus look any different in vinegar (about pH 3) and in dilute hydrochloric acid (about pH 1)?",
        "Universal indicator's colours match numbers on a scale. What do those numbers tell you?",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "s1-q24",
      topic: "aa",
      section: "aa-investigation",
      difficulty: "challenge",
      question: "A student compares three brands of antacid. For each brand, she puts 50 cm³ of the same dilute hydrochloric acid into a beaker with a few drops of universal indicator, then adds the antacid one spatula at a time, stirring, until the indicator turns green. She counts how many spatulas are needed. What is the independent variable?",
      options: [
        "The number of spatulas of antacid added",
        "The brand of antacid being tested",
        "The volume of acid in the beaker",
        "The colour the indicator turns at the end",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Counting spatulas is the main thing she does, so it feels important — but it's what she measures, so it's the dependent variable.",
        "The brand of antacid is the one thing she changes on purpose between tests, so it is the independent variable.",
        "The volume is a number in the method, so it can look like a variable to pick — but it's kept the same (50 cm³) every time, so it's a control variable.",
        "The colour change is what she watches for, but green is just the signal to stop — it's the same for every brand, so it isn't the variable being changed.",
      ],
      explanation:
        "The **independent variable** is the one thing **you change** (the brand of antacid); the **dependent variable** is what **you measure** (the number of spatulas needed to reach green); **control variables** are kept the **same** to make it a fair test (volume and concentration of acid, size of each spatula-full, amount of indicator). In a results table, the independent variable goes in the **first column**. Memory trick: **I** change the **I**ndependent; the **D**ependent is the **D**ata I collect.",
      hints: [
        "Ask yourself: what is DIFFERENT each time she does the test?",
        "The number she counts is her result. Is that something she changes, or something she finds out?",
        "The independent variable is the one thing the scientist chooses to change on purpose. Which option fits that?",
      ],
      strategy: "Think like a scientist (fair test)",
    },
    {
      id: "s1-q25",
      topic: "aa",
      section: "aa-uses",
      difficulty: "challenge",
      question: "A farmer tests her soil and finds it has a pH of 5. Her crop grows best in soil that is about pH 7. What should she add to the soil, and why?",
      options: [
        "Lime (calcium hydroxide), a base that neutralises the acid",
        "Dilute acid, because adding acid will raise the pH up to 7",
        "Lots of water, to dilute the soil acid until it is neutral",
        "Table salt, because salts are neutral and cancel out acid",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Lime is a base, so it neutralises acid in the soil and raises the pH towards 7 — that's why farmers spread it on acidic fields.",
        "It's easy to get the direction muddled, but adding acid makes soil MORE acidic and LOWERS the pH further below 5. To raise the pH, you need a base.",
        "Water is neutral, so it sounds gentle and safe — but it can't neutralise an acid. It only spreads it out, so the soil would stay acidic.",
        "Salts are made BY neutralisation, so this sounds sensible — but table salt (sodium chloride) is not a base, so it can't neutralise the acid (and it would harm the crops, too).",
      ],
      explanation:
        "Soil at **pH 5 is acidic**, so the farmer needs to **raise the pH to 7** — that means adding a **base**, which **neutralises** the acid (acid + base → salt + water). Farmers spread **lime** (calcium hydroxide) on acidic fields, and lakes damaged by acid rain are treated with lime in the same way. Careful: 'lime' here is a white chemical powder, not the sour green fruit — the fruit contains citric acid and would make things worse!",
      hints: [
        "Is pH 5 acidic, neutral or alkaline?",
        "To move the pH from 5 up to 7, does she need to add an acid or a base?",
        "Which option is a base — and what does a base do to an acid?",
      ],
      strategy: "Apply it to a new situation",
    },
  ],
};
