import type { MCQ, QuestionSet } from "../types";

export const MCQ_SET_4: QuestionSet<MCQ> = {
  id: "mcq-4",
  title: "Set 4 · Mixed mock B (stretch)",
  subtitle: "Data, practicals and cross-topic thinking — the hardest set",
  topic: "mixed",
  questions: [
    // ───────────── WARMUP ─────────────
    {
      id: "s4-q01",
      topic: "aa",
      section: "aa-hazards",
      difficulty: "warmup",
      question: "Which keyword means 'the chance that a hazard will actually cause harm'?",
      options: ["Hazard", "Precaution", "Risk", "Corrosive"],
      answerIndex: 2,
      optionFeedback: [
        "Hazard appears inside the definition, which makes it tempting — but a hazard is the thing that could cause harm (like a bottle of acid), not the chance of harm happening.",
        "A precaution is an action you take to lower the risk, such as wearing eye protection — it reduces the chance of harm, but it isn't the chance itself.",
        "Risk is the chance (how likely it is) that a hazard will actually cause harm.",
        "Corrosive sounds like a safety word, but it describes a kind of hazard — a substance that can destroy metals, stonework and skin — not how likely harm is.",
      ],
      explanation:
        "Three linked safety words: a **hazard** is something that could cause harm (e.g. a concentrated acid); the **risk** is the chance that the hazard actually causes harm; a **precaution** is an action that reduces the risk (e.g. wearing eye protection or using a more dilute acid). A bottle of acid on the shelf is always a hazard, but good precautions keep the risk small. Memory trick: **hazard = the thing, risk = the chance, precaution = the action**.",
      hints: [
        "The definition already uses the word 'hazard', so the answer must be a different idea. Is it describing a thing, an action or a chance?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s4-q02",
      topic: "an",
      section: "an-diet",
      difficulty: "warmup",
      question: "Not eating enough protein can make children very weak. This is an example of…",
      options: ["Malnutrition", "Dehydration", "Obesity", "Scurvy"],
      answerIndex: 0,
      optionFeedback: [
        "Malnutrition means a poor diet that leads to health problems — and too little protein is exactly that.",
        "Dehydration is also a 'not enough' problem, but it means not enough water in the body (causing tiredness and headaches), not too little protein.",
        "Obesity is caused by diet too, but it means being very overweight from taking in too much energy — not a shortage of protein.",
        "Scurvy is a deficiency disease, which makes it tempting, but it is caused by a lack of vitamin C, not protein.",
      ],
      explanation:
        "**Malnutrition** is a poor diet that leads to health problems — eating too little (or too much) of the nutrients you need. Protein is needed for **growth and repair**, so children who don't get enough can't build and repair muscle, and they become very weak. Good vegetarian protein sources include lentils, chickpeas, tofu and paneer. Memory trick: *mal-* means 'bad', so **malnutrition = bad nutrition**.",
      hints: [
        "Match each option to its cause: too little water? too much energy? too little vitamin C? Which one is left for a poor diet in general?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s4-q03",
      topic: "aa",
      section: "aa-salts",
      difficulty: "warmup",
      question: "When an acid reacts with an alkali, a salt is made. What is the other product?",
      options: ["Hydrogen", "Carbon dioxide", "Chlorine", "Water"],
      answerIndex: 3,
      optionFeedback: [
        "Acids do contain hydrogen, which makes this tempting — but in neutralisation the hydrogen from the acid ends up in the water that is made, not as hydrogen gas.",
        "Carbon dioxide is the gas you might remember from fizzing reactions, but an acid and an alkali don't fizz when they react — the only products are a salt and water.",
        "Hydrochloric acid does contain chlorine, but it ends up inside the salt as a chloride (e.g. sodium chloride) — no chlorine gas is made.",
        "The general equation is acid + alkali → salt + water, so water is the other product.",
      ],
      explanation:
        "Every neutralisation follows the school's general equation: **acid + alkali → salt + water**. For example, hydrochloric acid + sodium hydroxide → **sodium chloride + water**. That's why you end up with a salt solution, and why you evaporate the water off to get salt crystals. Memory trick: neutralisation makes 'salt water' — a **salt** and **water**.",
      hints: [
        "Think about making salt crystals: after neutralising, you heat the solution in an evaporating basin. What is being evaporated off?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s4-q04",
      topic: "an",
      section: "an-system",
      difficulty: "warmup",
      question: "After you swallow, how does food get from your mouth to your stomach?",
      options: [
        "It falls down the oesophagus because of gravity",
        "Muscle contractions push it down the oesophagus",
        "Saliva washes it down the oesophagus into the stomach",
        "The stomach churns and sucks it down the oesophagus",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Gravity helps a little, but it isn't what moves the food — you can even swallow while lying down, because muscles do the pushing.",
        "Muscles in the wall of the oesophagus contract behind the food, squeezing it down into the stomach.",
        "Saliva makes food moist and slippery so it is easier to swallow, but it doesn't move the food along — the muscles of the oesophagus do.",
        "The stomach does churn food, but only once the food has arrived — it can't suck food down; the oesophagus muscles push it there.",
      ],
      explanation:
        "The **oesophagus** (gullet) is the tube that connects the mouth to the stomach. Food is **pushed down by contractions of the muscles** in its wall — waves of squeezing called **peristalsis** — which is why you can swallow even when lying down. The same muscle squeezing moves food along the whole digestive system. Picture squeezing toothpaste along its tube from behind.",
      hints: [
        "Could you still swallow a mouthful of rice while lying down? What does that tell you about gravity?",
      ],
      strategy: "Follow the food",
    },
    {
      id: "s4-q05",
      topic: "aa",
      section: "aa-indicators",
      difficulty: "warmup",
      question: "A solution is tested with litmus paper. Red litmus turns blue, and blue litmus stays blue. What can you conclude?",
      options: [
        "The solution is acidic",
        "The solution is neutral",
        "The solution is alkaline",
        "The solution is strongly alkaline",
      ],
      answerIndex: 2,
      optionFeedback: [
        "It's easy to mix up which paper does what, but acids turn blue litmus red — here the blue paper stayed blue, so the solution can't be acidic.",
        "Blue litmus staying blue might look like 'no change', but in a neutral solution neither paper changes — here the red paper turned blue, so it isn't neutral.",
        "Alkalis turn red litmus blue, and blue litmus stays blue in an alkali — exactly these results.",
        "It is alkaline, but litmus only has two colours, so it can't show how strong an alkali is — you'd need universal indicator or a pH probe for that.",
      ],
      explanation:
        "Litmus has just two colours. **Acids turn blue litmus red; alkalis turn red litmus blue**; in a neutral solution neither paper changes. Here the red paper turned blue, so the solution is **alkaline** (pH above 7) — and blue litmus staying blue fits that. Litmus can't tell you how strong an acid or alkali is, but universal indicator can. Memory trick: **R**ed → **B**lue = **R**eally **B**asic (alkaline).",
      hints: ["Which paper changed colour? What type of solution makes that paper change?"],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s4-q06",
      topic: "an",
      section: "an-nutrients",
      difficulty: "warmup",
      question: "Which nutrient cannot be digested, but is still an important part of a healthy diet?",
      options: ["Fibre", "Protein", "Starch", "Fat"],
      answerIndex: 0,
      optionFeedback: [
        "Our digestive enzymes can't break fibre down, but it keeps food and faeces moving through the gut and prevents constipation.",
        "Protein molecules are large, so you might think they're too big to digest — but protease breaks them into amino acids in the stomach and small intestine.",
        "Starch is a large insoluble molecule, so it might seem hard to digest — but amylase starts breaking it into sugars in your mouth, and digestion finishes in the small intestine.",
        "Fat can seem like something the body just stores, but it is digested — bile emulsifies it and lipase breaks it into fatty acids and glycerol.",
      ],
      explanation:
        "**Fibre** is the one nutrient that our digestive enzymes **cannot break down**, so it is never absorbed. It is still vital: it **keeps food and faeces moving** along the digestive system and **prevents constipation**. Good sources are wholegrain bread, brown rice, lentils, chickpeas, fruit and vegetables. Vitamins, minerals and water aren't digested either — but that's because they are already small enough to be absorbed.",
      hints: ["Think about which nutrient's job is to help you go to the toilet regularly."],
      strategy: "Recall the keyword",
    },

    // ───────────── CORE ─────────────
    {
      id: "s4-q07",
      topic: "aa",
      section: "aa-ph",
      difficulty: "core",
      question: "A student measures the pH of some rainwater, first with universal indicator and then with a pH probe. What is the main advantage of the pH probe?",
      options: [
        "It shows how strongly acidic a solution is, which universal indicator can't",
        "It changes to a brighter colour that is easier to match to the chart",
        "It tells you the name of the acid or alkali in the solution",
        "It gives an accurate number, so no one has to judge a colour by eye",
      ],
      answerIndex: 3,
      optionFeedback: [
        "A probe sounds more advanced, which makes this tempting — but universal indicator already shows strength: red means strongly acidic and yellow means weakly acidic.",
        "Brighter colours would help, but a pH probe doesn't change colour at all — it shows the pH as a number on a screen, so colour-matching is exactly the step it avoids.",
        "A probe is high-tech, but it only measures pH — it can't tell you which acid or alkali is present, and different acids can give similar readings.",
        "The probe shows the pH as a number, so there's no guessing between similar colours — the reading is more accurate and doesn't depend on whose eyes are judging.",
      ],
      explanation:
        "Universal indicator shows pH as a **colour** that you match to a chart **by eye** — and neighbouring colours (like yellow and green) can look alike, so two people might read different pH values. A **pH probe (pH meter)** shows the pH as a **number**, so it is **more accurate** and doesn't depend on anyone's judgement. Both can tell you whether a solution is acidic, neutral or alkaline, and how strongly — the probe just does it more precisely.",
      hints: [
        "Think about what you actually do with universal indicator after it changes colour. Which step could go wrong?",
        "Two students look at the same yellowish-green colour. Would they always agree on the pH? Would they disagree about a number on a screen?",
      ],
      strategy: "Compare and contrast",
    },
    {
      id: "s4-q08",
      topic: "an",
      section: "an-food-tests",
      difficulty: "core",
      question: "A student wants to test crushed peanuts for fat. Which method and result are correct?",
      options: [
        "Shake with water, then pour the liquid into ethanol — milky white means fat",
        "Shake with ethanol, then pour the liquid into water — milky white means fat",
        "Add ethanol and heat in a hot water bath — brick red means fat",
        "Shake with ethanol, then pour the liquid into water — a clear liquid means fat",
      ],
      answerIndex: 1,
      optionFeedback: [
        "This uses the right two liquids, but in the wrong order — fat doesn't dissolve in water, so it has to be dissolved in ethanol first.",
        "Fat dissolves in ethanol; poured into water, it comes out as tiny droplets that make a milky white emulsion.",
        "A hot water bath and brick red are easy to mix up with this test, but they belong to the Benedict's test for sugar — the fat test needs no heating at all (and ethanol is flammable).",
        "The method is right but the result is back to front — a milky white (cloudy) layer means fat is present; if the liquid stays clear, there is no fat.",
      ],
      explanation:
        "The **emulsion test** for fat (lipid): first **shake the food with ethanol**, which dissolves any fat, then **pour the ethanol into water**. Fat can't dissolve in water, so it comes out as tiny droplets that make a **milky white emulsion** (a cloudy layer); if the liquid stays clear, there is no fat. Memory trick: **E before W** — Ethanol first, then Water, just like in the alphabet.",
      hints: [
        "Fat dissolves in one of these liquids but not in the other. Which one must the fat dissolve in first?",
        "The positive result appears when dissolved fat is suddenly put into a liquid it can't dissolve in. What would millions of tiny fat droplets look like?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s4-q09",
      topic: "aa",
      section: "aa-hazards",
      difficulty: "core",
      question: "Which hazard symbol would you expect on a bottle of concentrated sulfuric acid, and why?",
      options: [
        "Corrosive — it can destroy skin, eyes and metals",
        "Exclamation mark (irritant) — it may only cause mild irritation",
        "Flame (flammable) — acids catch fire easily",
        "Skull and crossbones (toxic) — its fumes are poisonous to breathe",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Concentrated acids carry the corrosive symbol because they can destroy living tissue such as skin and eyes, and even metals and stonework.",
        "The exclamation mark is usually found on dilute acids, which have fewer acid particles in the same volume — a concentrated acid is far more dangerous than an irritant.",
        "Acid 'burns' on skin make the flame tempting, but that damage is chemical (corrosion), not fire — sulfuric acid is not flammable.",
        "Acid is dangerous, so poison sounds right — but the skull and crossbones is for toxic substances, and concentrated sulfuric acid's danger is that it destroys skin and eyes on contact.",
      ],
      explanation:
        "Concentrated acids and alkalis carry the **corrosive** symbol: a corrosive substance can **destroy metals, stonework and skin**, and can badly damage eyes. Dilute acids have **fewer acid particles in the same volume**, so they are less hazardous and often carry the **exclamation mark (irritant)** symbol instead. Precautions such as wearing eye protection and using the most dilute acid that will do the job reduce the risk.",
      hints: [
        "Is this acid dilute or concentrated? Which kind usually gets the more serious symbol?",
        "When an acid 'burns' skin, is anything actually on fire — or is the acid eating away at the skin?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s4-q10",
      topic: "an",
      section: "an-diet",
      difficulty: "core",
      question: "Use the nutrition information. Which food would be best for growth and repair, and why?",
      table: {
        caption: "Nutrition information per 100 g",
        headers: ["Food", "Protein (g)", "Carbohydrate (g)", "Fat (g)", "Fibre (g)"],
        rows: [
          ["Paneer", "18", "3", "20", "0"],
          ["Brown rice", "3", "23", "1", "2"],
          ["Apple", "0.3", "14", "0.2", "2.4"],
          ["Chickpeas (cooked)", "9", "27", "3", "8"],
        ],
      },
      options: [
        "Chickpeas, because they have the most carbohydrate",
        "Paneer, because it has the most fat",
        "Paneer, because it has the most protein",
        "Apple, because it has the least fat",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Chickpeas do have the most carbohydrate (27 g), but carbohydrate is for energy, not growth and repair — and they have only half as much protein as paneer.",
        "Paneer is the right food but for the wrong reason — fat is for stored energy and insulation; it's paneer's protein that helps growth and repair.",
        "Protein is the nutrient for growth and repair, and paneer has the most: 18 g per 100 g, twice as much as chickpeas.",
        "Low-fat foods can be part of a healthy diet, but growth and repair needs protein — and the apple has almost none (0.3 g).",
      ],
      explanation:
        "First link the job to the nutrient: **growth and repair → protein**. Then read down the **Protein (g)** column: paneer 18 g, chickpeas 9 g, brown rice 3 g, apple 0.3 g — so **paneer** has the most protein per 100 g. Don't be distracted by the other columns: carbohydrate and fat are for energy, and fibre keeps food moving through the gut. Chickpeas and lentils are good vegetarian protein sources too.",
      hints: [
        "Which nutrient does the body use for growth and repair?",
        "Find that nutrient's column in the table and compare the numbers going down it.",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "s4-q11",
      topic: "aa",
      section: "aa-neutralisation",
      difficulty: "core",
      question: "Why is neutralisation described as a chemical reaction?",
      options: [
        "Because the indicator in the mixture changes colour",
        "Because the alkali simply dilutes the acid to pH 7",
        "Because the two solutions mix and dissolve together",
        "Because new substances, a salt and water, are made",
      ],
      answerIndex: 3,
      optionFeedback: [
        "The colour change is a useful clue that something is happening, but it only shows the pH has changed — what makes neutralisation a chemical reaction is that new substances are made.",
        "Adding alkali can look like 'watering down' the acid, but dilution only spreads acid particles out and makes nothing new — the alkali reacts with the acid to make a salt and water.",
        "The solutions do mix, but mixing and dissolving on their own don't make anything new. In neutralisation the acid and alkali react and are used up, and new substances form.",
        "A chemical reaction is a change in which new substances are made — and neutralisation makes a salt and water.",
      ],
      explanation:
        "The school's definition: a **chemical reaction** is a change in which **new substances are made**. In neutralisation the acid and alkali (the **reactants**) are used up and a **salt and water** (the **products**) are made — e.g. hydrochloric acid + sodium hydroxide → sodium chloride + water. Sodium chloride wasn't in the beaker at the start, so something new has formed. Clues like an indicator changing colour or the mixture warming up suggest a reaction, but the definition is about the new substances.",
      hints: [
        "What is the difference between just mixing two things and making them react?",
        "Compare what is in the beaker at the start with what is there at the end. Is there anything that wasn't there before?",
      ],
      strategy: "Recall the keyword",
    },
    {
      id: "s4-q12",
      topic: "an",
      section: "an-system",
      difficulty: "core",
      question: "Which two organs are part of the digestive system, but food does NOT pass through them?",
      options: [
        "The oesophagus and the rectum",
        "The liver and the pancreas",
        "The liver and the stomach",
        "The pancreas and the small intestine",
      ],
      answerIndex: 1,
      optionFeedback: [
        "These organs don't digest much, which makes them tempting — but food does pass through both: the oesophagus carries it to the stomach, and the rectum stores faeces before they leave through the anus.",
        "The liver makes bile and the pancreas makes enzymes; both are sent along tubes into the small intestine, but food never travels through these organs.",
        "The liver is right, but food does pass through the stomach — that's where it is churned with acid and enzymes.",
        "The pancreas is right, but the small intestine is on the food's path — it's where digestion finishes and digested food is absorbed.",
      ],
      explanation:
        "Food travels along one long tube: **mouth → oesophagus → stomach → small intestine → large intestine → rectum → anus**. The **liver** (which makes bile, stored in the gall bladder) and the **pancreas** (which makes enzymes) sit beside this tube and **add substances into the small intestine**, but food never passes through them. Think of them as delivery vans dropping off supplies, not stops on the food's route.",
      hints: [
        "Trace the food's route from mouth to anus. Which organs are on that route?",
        "Some organs only make substances (like bile and enzymes) and send them along tubes into the small intestine. Which are they?",
      ],
      strategy: "Follow the food",
    },
    {
      id: "s4-q13",
      topic: "aa",
      section: "aa-salts",
      difficulty: "core",
      question: "Lithium hydroxide is an alkali. Which word equation correctly shows its reaction with hydrochloric acid?",
      options: [
        "lithium hydroxide + hydrochloric acid → lithium chloride + water",
        "lithium hydroxide + hydrochloric acid → lithium chlorate + water",
        "lithium hydroxide + hydrochloric acid → lithium chloride + hydrogen",
        "lithium chloride + water → lithium hydroxide + hydrochloric acid",
      ],
      answerIndex: 0,
      optionFeedback: [
        "Metal from the alkali (lithium) + ending from the acid (hydrochloric → chloride), and water is always the other product.",
        "Chlorate looks a lot like chloride, but hydrochloric acid always makes a chloride — the -ate endings come from sulfuric acid (sulfate) and nitric acid (nitrate).",
        "Acids contain hydrogen, so this looks reasonable — but when an acid reacts with an alkali the other product is always water, not hydrogen.",
        "These are the right substances, but back to front — reactants go on the left of the arrow and products on the right, and lithium chloride is made, not used up.",
      ],
      explanation:
        "Name the salt in two steps: **first word from the metal** in the alkali (lithium hydroxide → **lithium**), **second word from the acid** (hydrochloric → **chloride**). The general equation acid + alkali → salt + water tells you the other product is **water**, and the **reactants** go on the left of the arrow with the **products** on the right. Memory trick: hydro**chlor**ic → **chlor**ide, **sulf**uric → **sulf**ate, **nitr**ic → **nitr**ate.",
      hints: [
        "The first word of the salt comes from the metal in the alkali. Where does the second word come from?",
        "Check three things in each equation: which side the reactants are on, the ending of the salt, and what the other product should be.",
      ],
      strategy: "Name the salt (metal first, acid second)",
    },
    {
      id: "s4-q14",
      topic: "an",
      section: "an-diet",
      difficulty: "core",
      question: "Which statement best explains why a person becomes obese?",
      options: [
        "They eat too much fat, and fat is the only nutrient that is stored as body fat",
        "They eat too little fibre, so food stays in their gut for too long",
        "They take in more energy than they use, so the extra is stored as fat",
        "They eat too little protein, so their muscles turn into fat instead",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Fatty foods are high in energy, so this is tempting — but any extra energy, including from carbohydrates like rice and bread, ends up stored as fat.",
        "Too little fibre can cause constipation, but it doesn't make someone obese — obesity comes from taking in more energy than the body uses.",
        "When the energy taken in from food is more than the energy used for living and activity, the extra is stored as fat; over time this leads to obesity.",
        "Weak muscles and extra fat can seem linked, but muscle can't turn into fat — they are different tissues. Weight gain happens when the energy taken in is more than the energy used.",
      ],
      explanation:
        "**Obesity** means being very overweight, which leads to health problems. It happens when a person regularly takes in **more energy from food than their body uses** — the **extra energy is stored as fat**. It doesn't matter whether the extra energy comes from fat, sugar or starch: too much of any of them adds up. Energy needs depend on age, size and how active you are, so a balanced diet plus exercise keeps 'energy in' and 'energy out' matched.",
      hints: [
        "Which nutrients give us energy? Is it only fat?",
        "Think of energy like a bank balance: energy in from food, energy out from living and moving. What happens to any energy that's left over?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s4-q15",
      topic: "aa",
      section: "aa-uses",
      difficulty: "core",
      question: "Acid rain has made a lake too acidic for fish to live in. Why do people sometimes add lime to the lake?",
      options: [
        "Lime is an acid, and adding one acid to another cancels them out",
        "Lime is a base, so it neutralises the acid and fish can survive",
        "Lime dilutes the acid in the lake until the water becomes alkaline",
        "Lime makes the lake strongly alkaline, which is the safest pH for fish",
      ],
      answerIndex: 1,
      optionFeedback: [
        "The fruit called a lime is acidic, which makes this tempting — but the lime added to lakes is a chemical base (such as calcium hydroxide), and adding an acid would make the lake even more acidic.",
        "Lime is a base: it reacts with the acid in the water and neutralises it, raising the pH back towards 7 so fish and plants can live there again.",
        "Adding a substance to a lake might sound like diluting it, but lime works by reacting — and diluting an acid can never make it alkaline anyway. Lime is a base that neutralises the acid.",
        "Alkaline is the opposite of acidic, so this sounds like a fix — but fish need water close to neutral, and strongly alkaline water would harm them too. Just enough lime is added to neutralise the acid.",
      ],
      explanation:
        "**Lime** is a **base** (for example calcium hydroxide). When it is added to a lake damaged by **acid rain**, it reacts with the acid and **neutralises** it, raising the pH back towards 7 so fish and plants can survive. Farmers use lime in the same way to treat acidic soil. Don't confuse it with the fruit: lime juice is acidic, but the chemical lime is a base.",
      hints: [
        "To fix water that is too acidic, would you add an acid, a base or just more water?",
        "What pH do fish and plants need — very acidic, very alkaline or close to neutral?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "s4-q16",
      topic: "an",
      section: "an-absorption",
      difficulty: "core",
      question: "Which change would make the small intestine absorb digested food faster?",
      options: [
        "Thicker villus walls, so the villi are stronger",
        "Fewer capillaries, so the blood flows past more slowly",
        "Flatter villi, so food passes through more quickly",
        "More, longer villi, so the surface area is larger",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Stronger might sound better, but thicker walls make a longer distance for digested food to cross into the blood, so absorption would slow down — that's why the walls are only one cell thick.",
        "Slower blood might sound like more time to absorb, but fewer capillaries means a poorer blood supply to carry digested food away, so absorption would slow down.",
        "Food rushing through might sound efficient, but flatter villi mean a smaller surface area, so less digested food could be absorbed.",
        "More and longer villi give a bigger surface area, so more digested food can be absorbed into the blood at the same time.",
      ],
      explanation:
        "The small intestine is adapted for fast absorption in three ways: **villi** give a **very large surface area**; the walls are **one cell thick**, so digested food has only a short distance to travel; and **lots of capillaries** give a good blood supply. Anything that increases the surface area — like more or longer villi — speeds up absorption, while thicker walls, fewer capillaries or flatter villi slow it down. Memory trick — the **3 Ls**: **L**arge surface area, **L**ittle distance, **L**ots of blood.",
      hints: [
        "The small intestine already has three adaptations for absorption. Can you name them?",
        "For each option, ask: does it make the surface area bigger, the distance shorter or the blood supply better — or the opposite?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "s4-q17",
      topic: "aa",
      section: "aa-investigation",
      difficulty: "core",
      question: "Mia compares three antacids. Each time, she adds powdered antacid one spatula at a time to dilute hydrochloric acid with universal indicator, and counts how many spatulas it takes to turn the indicator green. What must she keep the same to make it a fair test?",
      options: [
        "The volume and concentration of the acid",
        "The type of antacid she adds to each beaker",
        "The number of spatulas of antacid needed",
        "Only the volume of acid — its concentration can vary",
      ],
      answerIndex: 0,
      optionFeedback: [
        "More acid, or stronger acid, would need more antacid to neutralise it — so the volume and concentration of the acid must be the same every time.",
        "The type of antacid is central to the experiment, but it's the independent variable — the thing she changes on purpose to compare the remedies — so it can't be kept the same.",
        "Counting spatulas is a key part of the method, but it's the dependent variable — what she measures — so it is expected to be different for each antacid.",
        "Keeping the volume the same is a good start, but a more concentrated acid has more acid particles in the same volume and would need more antacid, so the concentration must be the same too.",
      ],
      explanation:
        "In a fair test you change **one** thing, measure **one** thing and keep everything else the same.\n\n- **Independent variable** (you change it): the type of antacid\n- **Dependent variable** (you measure it): the number of spatulas needed to turn the indicator green\n- **Control variables** (keep them the same): the **volume and concentration of the acid**, the indicator, stirring and temperature\n\nMemory trick: the **D**ependent variable **D**epends on what you change.",
      hints: [
        "Which option is the thing Mia changes on purpose, and which is the thing she measures? Neither of those can be kept the same.",
        "If one beaker held stronger acid than another, would it need the same number of spatulas of antacid?",
      ],
      strategy: "Think like a scientist (fair test)",
    },
    {
      id: "s4-q18",
      topic: "an",
      section: "an-enzymes",
      difficulty: "core",
      question: "Starch digestion starts in the mouth, where amylase in saliva begins breaking starch into sugars. Where is starch digestion completed?",
      options: [
        "In the stomach, where hydrochloric acid breaks it into sugars",
        "In the small intestine, where bile from the liver digests it",
        "In the small intestine, by carbohydrase from the pancreas",
        "In the large intestine, which digests any starch left over",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Stomach acid is strong, so it seems it could break anything down — but acid doesn't digest starch, and the stomach's enzyme is a protease, which only works on protein.",
        "The small intestine is the right place, but bile is the wrong substance — it isn't an enzyme; it emulsifies fat into small droplets and can't break starch into sugars.",
        "Carbohydrases (such as amylase) made in the pancreas are released into the small intestine, where they finish breaking starch into sugars that can be absorbed.",
        "The large intestine comes later, so it might seem like the place to finish the job — but by then digestion is over; it absorbs water from undigested leftovers to make faeces.",
      ],
      explanation:
        "Starch is digested by **carbohydrase** enzymes (amylase is one). Digestion **starts in the mouth** (amylase in saliva) and is **completed in the small intestine**, where carbohydrases **made in the pancreas** are released. The sugars made, such as glucose, are then **absorbed into the blood** through the villi. Each substance has its own job: the stomach's protease only digests protein, and bile only emulsifies fat.",
      hints: [
        "Which type of enzyme digests starch — and apart from saliva, which organ makes digestive enzymes and sends them into the gut?",
        "Digestion of every type of food finishes in the same organ, just before the digested food is absorbed. Which organ is that?",
      ],
      strategy: "Follow the food",
    },

    // ───────────── CHALLENGE ─────────────
    {
      id: "s4-q19",
      topic: "aa",
      section: "aa-ph",
      difficulty: "challenge",
      question: "A solution of an alkali has a pH of 12. A student adds a large volume of water to it. What happens to the pH?",
      options: [
        "It stays at 12, because water doesn't react with the alkali",
        "It falls towards 7, but it will always stay above 7",
        "It falls to exactly 7, because water neutralises the alkali",
        "It drops below 7 once enough water has been added",
      ],
      answerIndex: 1,
      optionFeedback: [
        "It's true that water doesn't react with the alkali, but it spreads the alkali particles out into a bigger volume — fewer particles in the same volume means the solution is less alkaline, so its pH falls.",
        "Diluting spreads the alkali particles out, so the solution becomes less alkaline and its pH moves down towards 7 — but water can never make it acidic.",
        "Water is neutral, which makes 7 tempting — but water doesn't neutralise anything; only an acid can neutralise an alkali. Adding water just moves the pH closer to 7.",
        "It's tempting to think enough water would flip it to acidic, but water is neutral, so it can never push an alkali below 7 — only adding an acid could do that.",
      ],
      explanation:
        "Diluting spreads the alkali particles out, so there are **fewer alkali particles in the same volume** and the solution becomes **less alkaline** — its pH falls **towards 7**. But water is neutral, so however much you add, the pH only gets **closer to 7**; it never goes below 7. To actually neutralise an alkali you must add an acid. The same rule works the other way: diluting an acid raises its pH towards 7, but never above 7.",
      hints: [
        "Does adding water add more alkali particles, or spread the same particles out?",
        "Is water acidic, neutral or alkaline? Could mixing an alkali with water ever give something more acidic than water itself?",
        "Diluting orange squash makes it weaker and weaker — but could it ever turn into the opposite of squash?",
      ],
      strategy: "Think about particles",
    },
    {
      id: "s4-q20",
      topic: "an",
      section: "an-bile",
      difficulty: "challenge",
      question: "Food leaving the stomach is acidic because it has been mixed with hydrochloric acid. What neutralises this acid in the small intestine?",
      options: [
        "Water, which dilutes the acid until it is neutral",
        "The villi, which absorb the acid into the bloodstream",
        "Bile, an acidic liquid that cancels out the acid",
        "Bile, an alkaline liquid that is made in the liver",
      ],
      answerIndex: 3,
      optionFeedback: [
        "Water does dilute the acid, which seems like it would help — but diluting only moves the pH towards 7; it can't neutralise the acid. That needs an alkali or base.",
        "The villi are in the small intestine and do absorb things, but only small, soluble digested food molecules — they don't remove the acid.",
        "Bile is the right liquid, but an acid can't neutralise another acid — bile works because it is alkaline.",
        "Bile is made in the liver, stored in the gall bladder and released into the small intestine — it is alkaline, so it neutralises the stomach acid.",
      ],
      explanation:
        "Food leaving the stomach is acidic (hydrochloric acid), so in the small intestine it meets **bile** — made in the **liver** and stored in the **gall bladder** — which is **alkaline** and **neutralises** the acid. This is the Acids & Alkalis rule in action: only an alkali (or another base) can neutralise an acid, while water would just dilute it. Bile's other job is to **emulsify** fat into small droplets, giving lipase a bigger surface area to work on.",
      hints: [
        "From Acids & Alkalis: what kind of substance do you need to neutralise an acid?",
        "Which liquid, made by the liver and stored in the gall bladder, is released into the small intestine?",
        "Two options name the right liquid, but only one describes it correctly. Could an acid neutralise an acid?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "s4-q21",
      topic: "aa",
      section: "aa-neutralisation",
      difficulty: "challenge",
      question: "A beaker contains sodium hydroxide solution and universal indicator. Hydrochloric acid is added a little at a time, and the student keeps adding acid even after the solution has become neutral. How does the pH change?",
      options: [
        "Starts at about 13, falls to 7, then goes below 7",
        "Starts at about 1, rises to 7, then goes above 7",
        "Starts at about 13, falls to 7, then stays at 7",
        "Starts at about 13, falls towards 7 but never reaches it",
      ],
      answerIndex: 0,
      optionFeedback: [
        "The alkali in the beaker starts at a high pH; the acid neutralises it to pH 7, and any extra acid after that makes the solution acidic (below 7).",
        "This is what you'd see if acid were in the beaker and alkali were being added — but here the beaker starts with sodium hydroxide, an alkali, so the pH starts high.",
        "pH 7 feels like the end point of neutralisation, but once all the alkali is used up, the extra acid has nothing left to react with, so the solution becomes acidic.",
        "That's the rule for adding water, which only dilutes — acid is different: it reacts with the alkali, so it can bring the pH all the way to 7 and then below it.",
      ],
      explanation:
        "At the start the beaker holds only **alkali**, so the pH is high — about 13, with the indicator **purple**. Each bit of acid **neutralises** some of the alkali, so the pH falls; when exactly enough acid has been added, the solution is **neutral, pH 7 (green)**. After that there's no alkali left, so the **extra acid makes the solution acidic** and the pH drops below 7, with the indicator moving towards red. Don't mix this up with adding water, which only moves the pH towards 7 and never past it.",
      hints: [
        "What is in the beaker at the very start — acid or alkali? So is the starting pH high or low?",
        "When the solution is exactly neutral, how much alkali is left for any new acid to react with?",
        "If the extra acid has nothing to react with, what does it do to the pH of the solution?",
      ],
      strategy: "Use the pH scale",
    },
    {
      id: "s4-q22",
      topic: "an",
      section: "an-enzymes",
      difficulty: "challenge",
      question: "Some protease is mixed with starch at body temperature, but none of the starch is digested. Why not?",
      options: [
        "Protease is a living thing, so it dies once it is outside the body",
        "Protease is used up as soon as it has broken down one molecule",
        "Its shape only fits protein molecules, like a lock fits one key",
        "Starch is already small and soluble, so it does not need digesting",
      ],
      answerIndex: 2,
      optionFeedback: [
        "Enzymes are made by living cells, which makes this tempting — but enzymes themselves are proteins, not living things, so they can't die.",
        "Enzymes are not used up — the same enzyme can work again and again. And even if it were used up, it would still have digested a little starch first.",
        "Enzymes are specific: protease's shape fits protein molecules, so starch doesn't fit — starch needs a carbohydrase such as amylase.",
        "Starch is actually a large, insoluble molecule — that's exactly why it has to be digested, but by a carbohydrase such as amylase, not by protease.",
      ],
      explanation:
        "Enzymes are **specific** — each one only works on one type of molecule. In the **lock-and-key** idea, the enzyme's shape is the lock, and only its own type of molecule (the key) fits it. Protease fits **protein** (making amino acids); starch needs a **carbohydrase** such as amylase, and fats need **lipase**. That's why your digestive system needs several different enzymes.",
      hints: [
        "Are enzymes living things? Are they used up when they work?",
        "Is starch a large insoluble molecule or a small soluble one?",
        "Think about your front-door key. Will it open every lock in your street?",
      ],
      strategy: "Eliminate wrong options",
    },
    {
      id: "s4-q23",
      topic: "aa",
      section: "aa-investigation",
      difficulty: "challenge",
      question: "Three antacids were each tested three times. Which antacid is the most effective at neutralising acid?",
      table: {
        caption: "Volume of acid neutralised by 1 g of antacid (cm³)",
        headers: ["Antacid", "Trial 1", "Trial 2", "Trial 3"],
        rows: [
          ["Calmo", "22", "24", "23"],
          ["Neutra", "30", "31", "29"],
          ["Settla", "18", "17", "19"],
        ],
      },
      options: [
        "Settla, because it used the least acid",
        "Neutra, because 1 g neutralised the most acid",
        "Calmo, because its results are the most consistent",
        "You can't tell, because the results vary between trials",
      ],
      answerIndex: 1,
      optionFeedback: [
        "Settla did use the least acid — but that means 1 g of it could only neutralise 18 cm³ of acid on average, so it is the least effective. A better antacid neutralises more acid per gram.",
        "Neutra's mean is 30 cm³ (Calmo 23 cm³, Settla 18 cm³) — the more acid 1 g can neutralise, the more effective the antacid.",
        "Calmo's results do look close together, but every antacid's results spread by just 2 cm³ — and consistency shows how reliable results are, not how much acid an antacid neutralises.",
        "The trials do vary a little (by 2 cm³), but the differences between the antacids are much bigger, and Neutra neutralised the most acid in every trial — so you can draw a conclusion.",
      ],
      explanation:
        "Work out each **mean**: add the three trials and divide by 3. Calmo (22 + 24 + 23) ÷ 3 = **23 cm³**; Neutra (30 + 31 + 29) ÷ 3 = **30 cm³**; Settla (18 + 17 + 19) ÷ 3 = **18 cm³**. Each number is how much acid **1 g** of antacid could neutralise, so a **bigger** volume means a more effective antacid — **Neutra**. Always check what the numbers measure before deciding whether the biggest or the smallest is best.",
      hints: [
        "Read the table title carefully: what does each number measure?",
        "Work out the mean for each antacid: add the three trials and divide by 3.",
        "A good antacid should be able to neutralise lots of stomach acid. Should you look for the biggest mean or the smallest?",
      ],
      strategy: "Read the data carefully",
    },
    {
      id: "s4-q24",
      topic: "an",
      section: "an-absorption",
      difficulty: "challenge",
      question: "A disease damages the small intestine so that its villi become flat. The person still eats a balanced diet. What would you expect to happen?",
      options: [
        "More food is absorbed, because a flat wall is easier for food to reach",
        "Nothing much, because the large intestine would absorb the food instead",
        "They gain weight, because the unabsorbed food builds up inside them",
        "Less digested food is absorbed, so they may lose weight and feel tired",
      ],
      answerIndex: 3,
      optionFeedback: [
        "A flat wall might seem easier for food to reach, but it has a much smaller surface area — and less surface area means less digested food can be absorbed.",
        "The large intestine does absorb something, but it's mainly water — it can't take over absorbing digested food, which happens in the small intestine.",
        "It might seem that food which isn't absorbed would build up, but it passes out in the faeces — and with less food reaching the blood, the person is more likely to lose weight.",
        "Flat villi mean a much smaller surface area, so less glucose, amino acids, fatty acids and glycerol reach the blood — the body is short of energy and of materials for growth and repair.",
      ],
      explanation:
        "**Villi** give the small intestine a **huge surface area** for absorbing digested food into the blood. If they become **flat**, the surface area falls, so **much less digested food is absorbed** — even though the person is eating normally. With less glucose for energy and fewer amino acids for growth and repair, they may **lose weight** and **feel tired** or weak. The large intestine can't make up for it, because it mainly absorbs water.",
      hints: [
        "What job do the villi do, and how does their shape help with that job?",
        "If the villi were flat, would the surface area be bigger or smaller? What would that do to absorption?",
        "If less glucose and fewer amino acids reach the blood, what happens to the person's energy and body mass?",
      ],
      strategy: "Apply it to a new situation",
    },
    {
      id: "s4-q25",
      topic: "aa",
      section: "aa-uses",
      difficulty: "challenge",
      question: "An indigestion tablet contains magnesium hydroxide, a base. Which salt is made when it neutralises the excess acid in your stomach?",
      options: ["Magnesium chloride", "Magnesium sulfate", "Magnesium nitrate", "Sodium chloride"],
      answerIndex: 0,
      optionFeedback: [
        "Stomach acid is hydrochloric acid, which makes chlorides — and the metal in the antacid is magnesium, so the salt is magnesium chloride (plus water).",
        "Sulfuric acid is a well-known lab acid, but the acid in your stomach is hydrochloric acid — sulfates only come from sulfuric acid.",
        "Nitric acid is another common lab acid, but nitrates only come from nitric acid — your stomach makes hydrochloric acid, so the salt must be a chloride.",
        "'Salt' makes most people think of table salt, but the first word of the salt comes from the metal in the base — this antacid contains magnesium, not sodium.",
      ],
      explanation:
        "This links both topics. Your **stomach** makes **hydrochloric acid** (it kills bacteria and gives the right conditions for protease). An antacid contains a **base** to neutralise the excess acid: **magnesium hydroxide + hydrochloric acid → magnesium chloride + water**. Name the salt as usual — **metal first** (magnesium), **acid second** (hydrochloric → chloride).",
      hints: [
        "Which acid does your stomach make? Look back at what the stomach does in Animal Nutrition.",
        "Name the salt in two halves: the first word from the metal in the antacid, the second from the acid.",
        "Your stomach makes hydrochloric acid. Which salt ending goes with hydrochloric acid?",
      ],
      strategy: "Name the salt (metal first, acid second)",
    },
  ],
};
